#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Primal_Roof_Outer_Corner_01

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Primal_Roof_Outer_Corner_01.Apollo_Primal_Roof_Outer_Corner_01_C
// 0x0008 (0x0AF0 - 0x0AE8)
class AApollo_Primal_Roof_Outer_Corner_01_C final : public ABuildingRoof
{
public:
	class UPrimitive_Structure_AmbAudioComponent_C* Primitive_Structure_AmbAudioComponent;             // 0x0AE8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_Primal_Roof_Outer_Corner_01_C">();
	}
	static class AApollo_Primal_Roof_Outer_Corner_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Primal_Roof_Outer_Corner_01_C>();
	}
};
static_assert(alignof(AApollo_Primal_Roof_Outer_Corner_01_C) == 0x000008, "Wrong alignment on AApollo_Primal_Roof_Outer_Corner_01_C");
static_assert(sizeof(AApollo_Primal_Roof_Outer_Corner_01_C) == 0x000AF0, "Wrong size on AApollo_Primal_Roof_Outer_Corner_01_C");
static_assert(offsetof(AApollo_Primal_Roof_Outer_Corner_01_C, Primitive_Structure_AmbAudioComponent) == 0x000AE8, "Member 'AApollo_Primal_Roof_Outer_Corner_01_C::Primitive_Structure_AmbAudioComponent' has a wrong offset!");

}

