#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_ArsenicCore_Claws_Base

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "B_Mantis_Weapon_Parent_classes.hpp"
#include "PhysicsCore_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_ArsenicCore_Claws_Base.B_ArsenicCore_Claws_Base_C
// 0x00E8 (0x1020 - 0x0F38)
class AB_ArsenicCore_Claws_Base_C : public AB_Mantis_Weapon_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_ArsenicCore_Claws_Base_C;         // 0x0F38(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      SwingFXNiagara_Offhand;                            // 0x0F40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class USkeletalMeshComponentBudgeted*         WeaponMesh_Offhand;                                // 0x0F48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UNiagaraComponent*                      SwingFXNiagara_Main;                               // 0x0F50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class FName                                   OffhandSocketName;                                 // 0x0F58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               WeaponRelativeRotation_Main;                       // 0x0F60(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FRotator                               WeaponRelativeRotation_Offhand;                    // 0x0F6C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	class FName                                   MainhandSocketName;                                // 0x0F78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                WeaponRelativeOffset_Main;                         // 0x0F80(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                WeaponRelativeOffset_Offhand;                      // 0x0F8C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   SwingFXSocketName;                                 // 0x0F98(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                ImpactLocation;                                    // 0x0FA0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FAC[0x4];                                      // 0x0FAC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     ImpactDecal;                                       // 0x0FB0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   ImpactDecalPositionSocketName;                     // 0x0FB8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FVector>                        MainHandDecalLocations;                            // 0x0FC0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FVector>                        OffHandDecalLocations;                             // 0x0FD0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          MainHandFirstDecalLocationIsSet;                   // 0x0FE0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          OffHandFirstDecalLocationIsSet;                    // 0x0FE1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          MainHandDecalLocationsReady;                       // 0x0FE2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          OffHandDecalLocationsReady;                        // 0x0FE3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ReadyToAddImpactDecal;                             // 0x0FE4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_FE5[0x3];                                      // 0x0FE5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DecalOffset;                                       // 0x0FE8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                DecalScale;                                        // 0x0FEC(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DebugDecals;                                       // 0x0FF8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_FF9[0x3];                                      // 0x0FF9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DualDecalGraceWindow;                              // 0x0FFC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             UnequipSound;                                      // 0x1000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             EquipSound;                                        // 0x1008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFXSystemAsset*                         MainHandDirectionalImpactFX;                       // 0x1010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFXSystemAsset*                         OffhandDirectionalImpactFX;                        // 0x1018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_ArsenicCore_Claws_Base(int32 EntryPoint);
	void SetReadyToAddImpactDecalsFalse();
	void TrySpawnDecal();
	void OnPlayImpactFX(const struct FHitResult& HitResult, EPhysicalSurface ImpactPhysicalSurface, class UFXSystemComponent* SpawnedPSC);
	void Swing_Right_2();
	void Swing_Right_End();
	void Swing_Right();
	void Swing_Left_2();
	void Swing_Left_End();
	void Swing_Left();
	void K2_OnUnEquip();
	void OnWeaponDetached();
	void OnWeaponAttached();
	void Bind_Dual_Melee_Swing_Events();
	void Unbind_Dual_Melee_Swing_Events();

	void CalculateDecalRotationFrom2Locations(TArray<struct FVector>& DecalLocations, struct FRotator* DecalRotation) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_ArsenicCore_Claws_Base_C">();
	}
	static class AB_ArsenicCore_Claws_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_ArsenicCore_Claws_Base_C>();
	}
};
static_assert(alignof(AB_ArsenicCore_Claws_Base_C) == 0x000008, "Wrong alignment on AB_ArsenicCore_Claws_Base_C");
static_assert(sizeof(AB_ArsenicCore_Claws_Base_C) == 0x001020, "Wrong size on AB_ArsenicCore_Claws_Base_C");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, UberGraphFrame_B_ArsenicCore_Claws_Base_C) == 0x000F38, "Member 'AB_ArsenicCore_Claws_Base_C::UberGraphFrame_B_ArsenicCore_Claws_Base_C' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, SwingFXNiagara_Offhand) == 0x000F40, "Member 'AB_ArsenicCore_Claws_Base_C::SwingFXNiagara_Offhand' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, WeaponMesh_Offhand) == 0x000F48, "Member 'AB_ArsenicCore_Claws_Base_C::WeaponMesh_Offhand' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, SwingFXNiagara_Main) == 0x000F50, "Member 'AB_ArsenicCore_Claws_Base_C::SwingFXNiagara_Main' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, OffhandSocketName) == 0x000F58, "Member 'AB_ArsenicCore_Claws_Base_C::OffhandSocketName' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, WeaponRelativeRotation_Main) == 0x000F60, "Member 'AB_ArsenicCore_Claws_Base_C::WeaponRelativeRotation_Main' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, WeaponRelativeRotation_Offhand) == 0x000F6C, "Member 'AB_ArsenicCore_Claws_Base_C::WeaponRelativeRotation_Offhand' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, MainhandSocketName) == 0x000F78, "Member 'AB_ArsenicCore_Claws_Base_C::MainhandSocketName' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, WeaponRelativeOffset_Main) == 0x000F80, "Member 'AB_ArsenicCore_Claws_Base_C::WeaponRelativeOffset_Main' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, WeaponRelativeOffset_Offhand) == 0x000F8C, "Member 'AB_ArsenicCore_Claws_Base_C::WeaponRelativeOffset_Offhand' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, SwingFXSocketName) == 0x000F98, "Member 'AB_ArsenicCore_Claws_Base_C::SwingFXSocketName' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, ImpactLocation) == 0x000FA0, "Member 'AB_ArsenicCore_Claws_Base_C::ImpactLocation' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, ImpactDecal) == 0x000FB0, "Member 'AB_ArsenicCore_Claws_Base_C::ImpactDecal' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, ImpactDecalPositionSocketName) == 0x000FB8, "Member 'AB_ArsenicCore_Claws_Base_C::ImpactDecalPositionSocketName' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, MainHandDecalLocations) == 0x000FC0, "Member 'AB_ArsenicCore_Claws_Base_C::MainHandDecalLocations' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, OffHandDecalLocations) == 0x000FD0, "Member 'AB_ArsenicCore_Claws_Base_C::OffHandDecalLocations' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, MainHandFirstDecalLocationIsSet) == 0x000FE0, "Member 'AB_ArsenicCore_Claws_Base_C::MainHandFirstDecalLocationIsSet' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, OffHandFirstDecalLocationIsSet) == 0x000FE1, "Member 'AB_ArsenicCore_Claws_Base_C::OffHandFirstDecalLocationIsSet' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, MainHandDecalLocationsReady) == 0x000FE2, "Member 'AB_ArsenicCore_Claws_Base_C::MainHandDecalLocationsReady' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, OffHandDecalLocationsReady) == 0x000FE3, "Member 'AB_ArsenicCore_Claws_Base_C::OffHandDecalLocationsReady' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, ReadyToAddImpactDecal) == 0x000FE4, "Member 'AB_ArsenicCore_Claws_Base_C::ReadyToAddImpactDecal' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, DecalOffset) == 0x000FE8, "Member 'AB_ArsenicCore_Claws_Base_C::DecalOffset' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, DecalScale) == 0x000FEC, "Member 'AB_ArsenicCore_Claws_Base_C::DecalScale' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, DebugDecals) == 0x000FF8, "Member 'AB_ArsenicCore_Claws_Base_C::DebugDecals' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, DualDecalGraceWindow) == 0x000FFC, "Member 'AB_ArsenicCore_Claws_Base_C::DualDecalGraceWindow' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, UnequipSound) == 0x001000, "Member 'AB_ArsenicCore_Claws_Base_C::UnequipSound' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, EquipSound) == 0x001008, "Member 'AB_ArsenicCore_Claws_Base_C::EquipSound' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, MainHandDirectionalImpactFX) == 0x001010, "Member 'AB_ArsenicCore_Claws_Base_C::MainHandDirectionalImpactFX' has a wrong offset!");
static_assert(offsetof(AB_ArsenicCore_Claws_Base_C, OffhandDirectionalImpactFX) == 0x001018, "Member 'AB_ArsenicCore_Claws_Base_C::OffhandDirectionalImpactFX' has a wrong offset!");

}

