#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Assault_Scrap_Athena

#include "Basic.hpp"

#include "B_Assault_Scrap_Athena_classes.hpp"
#include "B_Assault_Scrap_Athena_parameters.hpp"


namespace SDK
{

// Function B_Assault_Scrap_Athena.B_Assault_Scrap_Athena_C.ExecuteUbergraph_B_Assault_Scrap_Athena
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Assault_Scrap_Athena_C::ExecuteUbergraph_B_Assault_Scrap_Athena(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_Scrap_Athena_C", "ExecuteUbergraph_B_Assault_Scrap_Athena");

	Params::B_Assault_Scrap_Athena_C_ExecuteUbergraph_B_Assault_Scrap_Athena Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Assault_Scrap_Athena.B_Assault_Scrap_Athena_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_Assault_Scrap_Athena_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Assault_Scrap_Athena_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

