#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Daybreak_HoagiePart_Weapon

#include "Basic.hpp"

#include "B_Daybreak_HoagiePart_Weapon_classes.hpp"
#include "B_Daybreak_HoagiePart_Weapon_parameters.hpp"


namespace SDK
{

// Function B_Daybreak_HoagiePart_Weapon.B_Daybreak_HoagiePart_Weapon_C.ExecuteUbergraph_B_Daybreak_HoagiePart_Weapon
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Daybreak_HoagiePart_Weapon_C::ExecuteUbergraph_B_Daybreak_HoagiePart_Weapon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Daybreak_HoagiePart_Weapon_C", "ExecuteUbergraph_B_Daybreak_HoagiePart_Weapon");

	Params::B_Daybreak_HoagiePart_Weapon_C_ExecuteUbergraph_B_Daybreak_HoagiePart_Weapon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Daybreak_HoagiePart_Weapon.B_Daybreak_HoagiePart_Weapon_C.UnbindWeaponSwitchEvent
// (BlueprintCallable, BlueprintEvent)

void AB_Daybreak_HoagiePart_Weapon_C::UnbindWeaponSwitchEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Daybreak_HoagiePart_Weapon_C", "UnbindWeaponSwitchEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Daybreak_HoagiePart_Weapon.B_Daybreak_HoagiePart_Weapon_C.AdjustMeshTransform
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortWeapon*                      NewWeapon                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AFortWeapon*                      PrevWeapon                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Daybreak_HoagiePart_Weapon_C::AdjustMeshTransform(class AFortWeapon* NewWeapon, class AFortWeapon* PrevWeapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Daybreak_HoagiePart_Weapon_C", "AdjustMeshTransform");

	Params::B_Daybreak_HoagiePart_Weapon_C_AdjustMeshTransform Parms{};

	Parms.NewWeapon = NewWeapon;
	Parms.PrevWeapon = PrevWeapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Daybreak_HoagiePart_Weapon.B_Daybreak_HoagiePart_Weapon_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_Daybreak_HoagiePart_Weapon_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Daybreak_HoagiePart_Weapon_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

