#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_HeldObjectSocketManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_HeldObjectSocketManager.B_HeldObjectSocketManager_C
// 0x0048 (0x0828 - 0x07E0)
class AB_HeldObjectSocketManager_C final : public ABuildingGameplayActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x07E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x07E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	TArray<class AB_HeldObjectSocket_C*>          HeldObjectSockets;                                 // 0x07F0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, ExposeOnSpawn)
	TArray<struct FGameplayTagContainer>          CurrentTags;                                       // 0x0800(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FGameplayTagContainer>          DefaultCorrectTags;                                // 0x0810(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	bool                                          CombinationCorrect;                                // 0x0820(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	bool                                          SocketOrderMatters;                                // 0x0821(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_B_HeldObjectSocketManager(int32 EntryPoint);
	void OnCombinationCorrect();
	void ReceiveBeginPlay();
	void UpdateHeldObjectTags(class AB_HeldObjectSocket_C* ChangedSocket);
	void VerifyHeldObjectTags(TArray<struct FGameplayTagContainer>& CorrectTags, TArray<struct FGameplayTagContainer>& CurrentTags_0, bool OrderMatters, bool* IsValidMatch);
	void CheckTagMatches();
	void OnRep_CombinationCorrect();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_HeldObjectSocketManager_C">();
	}
	static class AB_HeldObjectSocketManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_HeldObjectSocketManager_C>();
	}
};
static_assert(alignof(AB_HeldObjectSocketManager_C) == 0x000008, "Wrong alignment on AB_HeldObjectSocketManager_C");
static_assert(sizeof(AB_HeldObjectSocketManager_C) == 0x000828, "Wrong size on AB_HeldObjectSocketManager_C");
static_assert(offsetof(AB_HeldObjectSocketManager_C, UberGraphFrame) == 0x0007E0, "Member 'AB_HeldObjectSocketManager_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AB_HeldObjectSocketManager_C, DefaultSceneRoot) == 0x0007E8, "Member 'AB_HeldObjectSocketManager_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(AB_HeldObjectSocketManager_C, HeldObjectSockets) == 0x0007F0, "Member 'AB_HeldObjectSocketManager_C::HeldObjectSockets' has a wrong offset!");
static_assert(offsetof(AB_HeldObjectSocketManager_C, CurrentTags) == 0x000800, "Member 'AB_HeldObjectSocketManager_C::CurrentTags' has a wrong offset!");
static_assert(offsetof(AB_HeldObjectSocketManager_C, DefaultCorrectTags) == 0x000810, "Member 'AB_HeldObjectSocketManager_C::DefaultCorrectTags' has a wrong offset!");
static_assert(offsetof(AB_HeldObjectSocketManager_C, CombinationCorrect) == 0x000820, "Member 'AB_HeldObjectSocketManager_C::CombinationCorrect' has a wrong offset!");
static_assert(offsetof(AB_HeldObjectSocketManager_C, SocketOrderMatters) == 0x000821, "Member 'AB_HeldObjectSocketManager_C::SocketOrderMatters' has a wrong offset!");

}

