#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Bow_ClusterBomb_Secondary_Athena

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function B_Prj_Bow_ClusterBomb_Secondary_Athena.B_Prj_Bow_ClusterBomb_Secondary_Athena_C.ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena
// 0x0010 (0x0010 - 0x0000)
struct B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetExplosionDelay_Delay;                  // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x0008(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena) == 0x000008, "Wrong alignment on B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena");
static_assert(sizeof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena) == 0x000010, "Wrong size on B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena");
static_assert(offsetof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena, EntryPoint) == 0x000000, "Member 'B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena::EntryPoint' has a wrong offset!");
static_assert(offsetof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena, CallFunc_GetExplosionDelay_Delay) == 0x000004, "Member 'B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena::CallFunc_GetExplosionDelay_Delay' has a wrong offset!");
static_assert(offsetof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena, CallFunc_K2_SetTimer_ReturnValue) == 0x000008, "Member 'B_Prj_Bow_ClusterBomb_Secondary_Athena_C_ExecuteUbergraph_B_Prj_Bow_ClusterBomb_Secondary_Athena::CallFunc_K2_SetTimer_ReturnValue' has a wrong offset!");

// Function B_Prj_Bow_ClusterBomb_Secondary_Athena.B_Prj_Bow_ClusterBomb_Secondary_Athena_C.GetExplosionDelay
// 0x0018 (0x0018 - 0x0000)
struct B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay final
{
public:
	float                                         Delay;                                             // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetValueAtLevel_ReturnValue;              // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValueAtLevel_ReturnValue_1;            // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay) == 0x000004, "Wrong alignment on B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay");
static_assert(sizeof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay) == 0x000018, "Wrong size on B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay");
static_assert(offsetof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay, Delay) == 0x000000, "Member 'B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay::Delay' has a wrong offset!");
static_assert(offsetof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay, Temp_bool_Variable) == 0x000004, "Member 'B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay, CallFunc_GetValueAtLevel_ReturnValue) == 0x000008, "Member 'B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay::CallFunc_GetValueAtLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay, CallFunc_GetValueAtLevel_ReturnValue_1) == 0x00000C, "Member 'B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay::CallFunc_GetValueAtLevel_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay, CallFunc_RandomFloatInRange_ReturnValue) == 0x000010, "Member 'B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay, K2Node_Select_Default) == 0x000014, "Member 'B_Prj_Bow_ClusterBomb_Secondary_Athena_C_GetExplosionDelay::K2Node_Select_Default' has a wrong offset!");

}

