#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Bow_Flame_Fireball

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "B_Prj_Athena_Generic_CurieFireball_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Prj_Bow_Flame_Fireball.B_Prj_Bow_Flame_Fireball_C
// 0x0050 (0x0940 - 0x08F0)
class AB_Prj_Bow_Flame_Fireball_C final : public AB_Prj_Athena_Generic_CurieFireball_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_Prj_Bow_Flame_Fireball_C;         // 0x08F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               P_GL_Ribbon_SmokeTrail;                            // 0x08F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_SurfaceTypeSoundComponent_C*        BP_SurfaceTypeSoundComponent;                      // 0x0900(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        LoopingAudioTell;                                  // 0x0908(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        IntoWaterEffects;                                  // 0x0910(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             HitWater_NoFire_Sound;                             // 0x0918(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BurnoutTime;                                       // 0x0920(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Impact_Point;                                      // 0x0924(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Impact_Sound;                                      // 0x0930(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_Prj_Bow_Flame_Fireball(int32 EntryPoint);
	void Play_Impact_Sound();
	void Burnout();
	void ReceiveBeginPlay();
	void BndEvt__WaterInteractionComponent_K2Node_ComponentBoundEvent_0_WaterInteractionOnEnterWater__DelegateSignature(class AFortWaterBodyActor* WaterBody, class UFortWaterInteractionComponent* WaterInteractionComponent_0, bool bIsFirstBody);
	void OnExploded(const TArray<class AActor*>& HitActors, const TArray<struct FHitResult>& HitResults);
	void OnStop(const struct FHitResult& Hit);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Prj_Bow_Flame_Fireball_C">();
	}
	static class AB_Prj_Bow_Flame_Fireball_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Prj_Bow_Flame_Fireball_C>();
	}
};
static_assert(alignof(AB_Prj_Bow_Flame_Fireball_C) == 0x000010, "Wrong alignment on AB_Prj_Bow_Flame_Fireball_C");
static_assert(sizeof(AB_Prj_Bow_Flame_Fireball_C) == 0x000940, "Wrong size on AB_Prj_Bow_Flame_Fireball_C");
static_assert(offsetof(AB_Prj_Bow_Flame_Fireball_C, UberGraphFrame_B_Prj_Bow_Flame_Fireball_C) == 0x0008F0, "Member 'AB_Prj_Bow_Flame_Fireball_C::UberGraphFrame_B_Prj_Bow_Flame_Fireball_C' has a wrong offset!");
static_assert(offsetof(AB_Prj_Bow_Flame_Fireball_C, P_GL_Ribbon_SmokeTrail) == 0x0008F8, "Member 'AB_Prj_Bow_Flame_Fireball_C::P_GL_Ribbon_SmokeTrail' has a wrong offset!");
static_assert(offsetof(AB_Prj_Bow_Flame_Fireball_C, BP_SurfaceTypeSoundComponent) == 0x000900, "Member 'AB_Prj_Bow_Flame_Fireball_C::BP_SurfaceTypeSoundComponent' has a wrong offset!");
static_assert(offsetof(AB_Prj_Bow_Flame_Fireball_C, LoopingAudioTell) == 0x000908, "Member 'AB_Prj_Bow_Flame_Fireball_C::LoopingAudioTell' has a wrong offset!");
static_assert(offsetof(AB_Prj_Bow_Flame_Fireball_C, IntoWaterEffects) == 0x000910, "Member 'AB_Prj_Bow_Flame_Fireball_C::IntoWaterEffects' has a wrong offset!");
static_assert(offsetof(AB_Prj_Bow_Flame_Fireball_C, HitWater_NoFire_Sound) == 0x000918, "Member 'AB_Prj_Bow_Flame_Fireball_C::HitWater_NoFire_Sound' has a wrong offset!");
static_assert(offsetof(AB_Prj_Bow_Flame_Fireball_C, BurnoutTime) == 0x000920, "Member 'AB_Prj_Bow_Flame_Fireball_C::BurnoutTime' has a wrong offset!");
static_assert(offsetof(AB_Prj_Bow_Flame_Fireball_C, Impact_Point) == 0x000924, "Member 'AB_Prj_Bow_Flame_Fireball_C::Impact_Point' has a wrong offset!");
static_assert(offsetof(AB_Prj_Bow_Flame_Fireball_C, Impact_Sound) == 0x000930, "Member 'AB_Prj_Bow_Flame_Fireball_C::Impact_Sound' has a wrong offset!");

}

