#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_ThrownConsumable

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function B_Prj_ThrownConsumable.B_Prj_ThrownConsumable_C.ExecuteUbergraph_B_Prj_ThrownConsumable
// 0x0278 (0x0278 - 0x0000)
struct B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AFortPlayerController*>          Temp_object_Variable;                              // 0x0008(0x0010)(ConstParm, ReferenceParm)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x002C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_2;        // 0x0038(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_3;        // 0x0044(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_4;        // 0x0050(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EFortTeamAffiliation>                  K2Node_MakeArray_Array;                            // 0x0060(0x0010)(ReferenceParm)
	uint8                                         CallFunc_GetActorTeam_ReturnValue;                 // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_Event_Hit_1;                                // 0x0074(0x0088)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x00FD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x00FE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_FF[0x1];                                       // 0x00FF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0108(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0114(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0120(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x012C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0148(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x015C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0164(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0170(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x017C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         CallFunc_GetActorTeam_ReturnValue_1;               // 0x017D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17E[0x2];                                      // 0x017E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<EFortTeamAffiliation>                  K2Node_MakeArray_Array_1;                          // 0x0188(0x0010)(ReferenceParm)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_199[0x3];                                      // 0x0199(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x019C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_Event_HitActors;                            // 0x01A8(0x0010)(ConstParm, ReferenceParm)
	TArray<struct FHitResult>                     K2Node_Event_HitResults;                           // 0x01B8(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	struct FHitResult                             K2Node_Event_Hit;                                  // 0x01C8(0x0088)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_1;          // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_OnCollision_OutResult;                    // 0x0251(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_252[0x2];                                      // 0x0252(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_OnCollision_OutMagnitude;                 // 0x0254(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_2;          // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_259[0x7];                                      // 0x0259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AFortPlayerController*>          Temp_object_Variable_1;                            // 0x0260(0x0010)(ConstParm, ReferenceParm)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0270(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable) == 0x000008, "Wrong alignment on B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable");
static_assert(sizeof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable) == 0x000278, "Wrong size on B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, EntryPoint) == 0x000000, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::EntryPoint' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, Temp_object_Variable) == 0x000008, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_IsDedicatedServer_ReturnValue) == 0x000018, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x00001C, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000020, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x00002C, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_K2_GetActorLocation_ReturnValue_2) == 0x000038, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_K2_GetActorLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_K2_GetActorLocation_ReturnValue_3) == 0x000044, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_K2_GetActorLocation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_K2_GetActorLocation_ReturnValue_4) == 0x000050, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_K2_GetActorLocation_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, K2Node_MakeArray_Array) == 0x000060, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_GetActorTeam_ReturnValue) == 0x000070, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_GetActorTeam_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, K2Node_Event_Hit_1) == 0x000074, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::K2Node_Event_Hit_1' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_IsValid_ReturnValue) == 0x0000FC, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_bBlockingHit) == 0x0000FD, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_bInitialOverlap) == 0x0000FE, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_Time) == 0x000100, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_Distance) == 0x000104, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_Location) == 0x000108, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_ImpactPoint) == 0x000114, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_Normal) == 0x000120, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_ImpactNormal) == 0x00012C, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_PhysMat) == 0x000138, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_HitActor) == 0x000140, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_HitComponent) == 0x000148, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_HitBoneName) == 0x000150, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_HitItem) == 0x000158, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_ElementIndex) == 0x00015C, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_FaceIndex) == 0x000160, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_TraceStart) == 0x000164, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_BreakHitResult_TraceEnd) == 0x000170, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_IsValid_ReturnValue_1) == 0x00017C, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_GetActorTeam_ReturnValue_1) == 0x00017D, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_GetActorTeam_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_GetInstigator_ReturnValue) == 0x000180, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_GetInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, K2Node_MakeArray_Array_1) == 0x000188, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_IsLocallyControlled_ReturnValue) == 0x000198, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_IsLocallyControlled_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_Multiply_VectorVector_ReturnValue) == 0x00019C, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, K2Node_Event_HitActors) == 0x0001A8, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::K2Node_Event_HitActors' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, K2Node_Event_HitResults) == 0x0001B8, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::K2Node_Event_HitResults' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, K2Node_Event_Hit) == 0x0001C8, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::K2Node_Event_Hit' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_IsDedicatedServer_ReturnValue_1) == 0x000250, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_IsDedicatedServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_OnCollision_OutResult) == 0x000251, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_OnCollision_OutResult' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_OnCollision_OutMagnitude) == 0x000254, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_OnCollision_OutMagnitude' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_IsDedicatedServer_ReturnValue_2) == 0x000258, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_IsDedicatedServer_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, Temp_object_Variable_1) == 0x000260, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000270, "Member 'B_Prj_ThrownConsumable_C_ExecuteUbergraph_B_Prj_ThrownConsumable::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");

// Function B_Prj_ThrownConsumable.B_Prj_ThrownConsumable_C.OnStop
// 0x0088 (0x0088 - 0x0000)
struct B_Prj_ThrownConsumable_C_OnStop final
{
public:
	struct FHitResult                             Hit;                                               // 0x0000(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(B_Prj_ThrownConsumable_C_OnStop) == 0x000004, "Wrong alignment on B_Prj_ThrownConsumable_C_OnStop");
static_assert(sizeof(B_Prj_ThrownConsumable_C_OnStop) == 0x000088, "Wrong size on B_Prj_ThrownConsumable_C_OnStop");
static_assert(offsetof(B_Prj_ThrownConsumable_C_OnStop, Hit) == 0x000000, "Member 'B_Prj_ThrownConsumable_C_OnStop::Hit' has a wrong offset!");

// Function B_Prj_ThrownConsumable.B_Prj_ThrownConsumable_C.OnBounce
// 0x0088 (0x0088 - 0x0000)
struct B_Prj_ThrownConsumable_C_OnBounce final
{
public:
	struct FHitResult                             Hit;                                               // 0x0000(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(B_Prj_ThrownConsumable_C_OnBounce) == 0x000004, "Wrong alignment on B_Prj_ThrownConsumable_C_OnBounce");
static_assert(sizeof(B_Prj_ThrownConsumable_C_OnBounce) == 0x000088, "Wrong size on B_Prj_ThrownConsumable_C_OnBounce");
static_assert(offsetof(B_Prj_ThrownConsumable_C_OnBounce, Hit) == 0x000000, "Member 'B_Prj_ThrownConsumable_C_OnBounce::Hit' has a wrong offset!");

// Function B_Prj_ThrownConsumable.B_Prj_ThrownConsumable_C.OnExploded
// 0x0020 (0x0020 - 0x0000)
struct B_Prj_ThrownConsumable_C_OnExploded final
{
public:
	TArray<class AActor*>                         HitActors;                                         // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<struct FHitResult>                     HitResults;                                        // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(B_Prj_ThrownConsumable_C_OnExploded) == 0x000008, "Wrong alignment on B_Prj_ThrownConsumable_C_OnExploded");
static_assert(sizeof(B_Prj_ThrownConsumable_C_OnExploded) == 0x000020, "Wrong size on B_Prj_ThrownConsumable_C_OnExploded");
static_assert(offsetof(B_Prj_ThrownConsumable_C_OnExploded, HitActors) == 0x000000, "Member 'B_Prj_ThrownConsumable_C_OnExploded::HitActors' has a wrong offset!");
static_assert(offsetof(B_Prj_ThrownConsumable_C_OnExploded, HitResults) == 0x000010, "Member 'B_Prj_ThrownConsumable_C_OnExploded::HitResults' has a wrong offset!");

// Function B_Prj_ThrownConsumable.B_Prj_ThrownConsumable_C.UserConstructionScript
// 0x0001 (0x0001 - 0x0000)
struct B_Prj_ThrownConsumable_C_UserConstructionScript final
{
public:
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(B_Prj_ThrownConsumable_C_UserConstructionScript) == 0x000001, "Wrong alignment on B_Prj_ThrownConsumable_C_UserConstructionScript");
static_assert(sizeof(B_Prj_ThrownConsumable_C_UserConstructionScript) == 0x000001, "Wrong size on B_Prj_ThrownConsumable_C_UserConstructionScript");
static_assert(offsetof(B_Prj_ThrownConsumable_C_UserConstructionScript, CallFunc_IsDedicatedServer_ReturnValue) == 0x000000, "Member 'B_Prj_ThrownConsumable_C_UserConstructionScript::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");

}

