#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Daybreak_HoagiePart_Throw

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function B_Prj_Daybreak_HoagiePart_Throw.B_Prj_Daybreak_HoagiePart_Throw_C.ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw
// 0x0290 (0x0290 - 0x0000)
struct B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerController*                  CallFunc_GetOwnerPlayerController_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortControllerComponent_ItemAttachedActor* CallFunc_GetComponentByClass_ReturnValue;          // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn;             // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMesh*                            K2Node_CustomEvent_Mesh;                           // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_SetStaticMesh_ReturnValue;                // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortWeaponItemDefinition*              CallFunc_GetWeaponData_ReturnValue;                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortWeaponRangedItemDefinition*        K2Node_DynamicCast_AsFort_Weapon_Ranged_Item_Definition; // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0059(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5A[0x6];                                       // 0x005A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue; // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_68[0x8];                                       // 0x0068(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_Map_Find_Value;                           // 0x0070(0x0030)(IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMesh*                            K2Node_DynamicCast_AsStatic_Mesh;                  // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x3];                                       // 0x00B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetRelativeTransform_SweepHitResult;   // 0x00B4(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsValidSoftObjectReference_ReturnValue;   // 0x013C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x013D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x013E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x013F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FHitResult                             K2Node_ComponentBoundEvent_ImpactResult;           // 0x0140(0x0088)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                K2Node_ComponentBoundEvent_ImpactVelocity;         // 0x01C8(0x000C)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D4[0x4];                                      // 0x01D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerController*                  CallFunc_GetOwnerPlayerController_ReturnValue_1;   // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x01E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E2[0x2];                                      // 0x01E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x01E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x01EC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x01F8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0204(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0210(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21C[0x4];                                      // 0x021C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0230(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0240(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x0244(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0248(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x024C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0258(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_264[0x4];                                      // 0x0264(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ADaybreak_HoagieVehicle_Repairable_C*   K2Node_DynamicCast_AsDaybreak_Hoagie_Vehicle_Repairable; // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0270(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_271[0x7];                                      // 0x0271(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerStateAthena*                 K2Node_DynamicCast_AsFort_Player_State_Athena;     // 0x0278(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0280(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_AttemptInstallVehiclePart_ReturnValue;    // 0x0281(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x0282(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw) == 0x000010, "Wrong alignment on B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw");
static_assert(sizeof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw) == 0x000290, "Wrong size on B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, EntryPoint) == 0x000000, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::EntryPoint' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_GetOwnerPlayerController_ReturnValue) == 0x000008, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_GetOwnerPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_GetComponentByClass_ReturnValue) == 0x000010, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_GetOwner_ReturnValue) == 0x000018, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_HasAuthority_ReturnValue) == 0x000020, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_DynamicCast_AsFort_Player_Pawn) == 0x000028, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_DynamicCast_AsFort_Player_Pawn' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_CustomEvent_Mesh) == 0x000038, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_CustomEvent_Mesh' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_IsValid_ReturnValue) == 0x000040, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_SetStaticMesh_ReturnValue) == 0x000041, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_SetStaticMesh_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_GetWeaponData_ReturnValue) == 0x000048, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_GetWeaponData_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_DynamicCast_AsFort_Weapon_Ranged_Item_Definition) == 0x000050, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_DynamicCast_AsFort_Weapon_Ranged_Item_Definition' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_DynamicCast_bSuccess_1) == 0x000058, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_IsValid_ReturnValue_1) == 0x000059, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue) == 0x000060, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_Map_Find_Value) == 0x000070, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_Map_Find_ReturnValue) == 0x0000A0, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_DynamicCast_AsStatic_Mesh) == 0x0000A8, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_DynamicCast_AsStatic_Mesh' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_DynamicCast_bSuccess_2) == 0x0000B0, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_K2_SetRelativeTransform_SweepHitResult) == 0x0000B4, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_K2_SetRelativeTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_IsValidSoftObjectReference_ReturnValue) == 0x00013C, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_IsValidSoftObjectReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_IsValid_ReturnValue_2) == 0x00013D, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_HasAuthority_ReturnValue_1) == 0x00013E, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_HasAuthority_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_IsValid_ReturnValue_3) == 0x00013F, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_ComponentBoundEvent_ImpactResult) == 0x000140, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_ComponentBoundEvent_ImpactResult' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_ComponentBoundEvent_ImpactVelocity) == 0x0001C8, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_ComponentBoundEvent_ImpactVelocity' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_GetOwnerPlayerController_ReturnValue_1) == 0x0001D8, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_GetOwnerPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_bBlockingHit) == 0x0001E0, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_bInitialOverlap) == 0x0001E1, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_Time) == 0x0001E4, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_Distance) == 0x0001E8, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_Location) == 0x0001EC, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_ImpactPoint) == 0x0001F8, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_Normal) == 0x000204, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_ImpactNormal) == 0x000210, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_PhysMat) == 0x000220, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_HitActor) == 0x000228, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_HitComponent) == 0x000230, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_HitBoneName) == 0x000238, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_HitItem) == 0x000240, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_ElementIndex) == 0x000244, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_FaceIndex) == 0x000248, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_TraceStart) == 0x00024C, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_BreakHitResult_TraceEnd) == 0x000258, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_DynamicCast_AsDaybreak_Hoagie_Vehicle_Repairable) == 0x000268, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_DynamicCast_AsDaybreak_Hoagie_Vehicle_Repairable' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_DynamicCast_bSuccess_3) == 0x000270, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_DynamicCast_AsFort_Player_State_Athena) == 0x000278, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_DynamicCast_AsFort_Player_State_Athena' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_DynamicCast_bSuccess_4) == 0x000280, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, CallFunc_AttemptInstallVehiclePart_ReturnValue) == 0x000281, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::CallFunc_AttemptInstallVehiclePart_ReturnValue' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw, K2Node_Event_EndPlayReason) == 0x000282, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ExecuteUbergraph_B_Prj_Daybreak_HoagiePart_Throw::K2Node_Event_EndPlayReason' has a wrong offset!");

// Function B_Prj_Daybreak_HoagiePart_Throw.B_Prj_Daybreak_HoagiePart_Throw_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct B_Prj_Daybreak_HoagiePart_Throw_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Prj_Daybreak_HoagiePart_Throw_C_ReceiveEndPlay) == 0x000001, "Wrong alignment on B_Prj_Daybreak_HoagiePart_Throw_C_ReceiveEndPlay");
static_assert(sizeof(B_Prj_Daybreak_HoagiePart_Throw_C_ReceiveEndPlay) == 0x000001, "Wrong size on B_Prj_Daybreak_HoagiePart_Throw_C_ReceiveEndPlay");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_ReceiveEndPlay, EndPlayReason) == 0x000000, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_ReceiveEndPlay::EndPlayReason' has a wrong offset!");

// Function B_Prj_Daybreak_HoagiePart_Throw.B_Prj_Daybreak_HoagiePart_Throw_C.BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileBounceDelegate__DelegateSignature
// 0x0094 (0x0094 - 0x0000)
struct B_Prj_Daybreak_HoagiePart_Throw_C_BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileBounceDelegate__DelegateSignature final
{
public:
	struct FHitResult                             ImpactResult;                                      // 0x0000(0x0088)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                ImpactVelocity;                                    // 0x0088(0x000C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Prj_Daybreak_HoagiePart_Throw_C_BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileBounceDelegate__DelegateSignature) == 0x000004, "Wrong alignment on B_Prj_Daybreak_HoagiePart_Throw_C_BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileBounceDelegate__DelegateSignature");
static_assert(sizeof(B_Prj_Daybreak_HoagiePart_Throw_C_BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileBounceDelegate__DelegateSignature) == 0x000094, "Wrong size on B_Prj_Daybreak_HoagiePart_Throw_C_BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileBounceDelegate__DelegateSignature");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileBounceDelegate__DelegateSignature, ImpactResult) == 0x000000, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileBounceDelegate__DelegateSignature::ImpactResult' has a wrong offset!");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileBounceDelegate__DelegateSignature, ImpactVelocity) == 0x000088, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_BndEvt__ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_OnProjectileBounceDelegate__DelegateSignature::ImpactVelocity' has a wrong offset!");

// Function B_Prj_Daybreak_HoagiePart_Throw.B_Prj_Daybreak_HoagiePart_Throw_C.UpdateStaticMesh
// 0x0008 (0x0008 - 0x0000)
struct B_Prj_Daybreak_HoagiePart_Throw_C_UpdateStaticMesh final
{
public:
	class UStaticMesh*                            Mesh_0;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_Prj_Daybreak_HoagiePart_Throw_C_UpdateStaticMesh) == 0x000008, "Wrong alignment on B_Prj_Daybreak_HoagiePart_Throw_C_UpdateStaticMesh");
static_assert(sizeof(B_Prj_Daybreak_HoagiePart_Throw_C_UpdateStaticMesh) == 0x000008, "Wrong size on B_Prj_Daybreak_HoagiePart_Throw_C_UpdateStaticMesh");
static_assert(offsetof(B_Prj_Daybreak_HoagiePart_Throw_C_UpdateStaticMesh, Mesh_0) == 0x000000, "Member 'B_Prj_Daybreak_HoagiePart_Throw_C_UpdateStaticMesh::Mesh_0' has a wrong offset!");

}

