#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Shotgun_Scrap_Athena

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "B_Ranged_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Shotgun_Scrap_Athena.B_Shotgun_Scrap_Athena_C
// 0x0008 (0x1358 - 0x1350)
class AB_Shotgun_Scrap_Athena_C final : public AB_Ranged_Generic_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_Shotgun_Scrap_Athena_C;           // 0x1350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_B_Shotgun_Scrap_Athena(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Shotgun_Scrap_Athena_C">();
	}
	static class AB_Shotgun_Scrap_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Shotgun_Scrap_Athena_C>();
	}
};
static_assert(alignof(AB_Shotgun_Scrap_Athena_C) == 0x000008, "Wrong alignment on AB_Shotgun_Scrap_Athena_C");
static_assert(sizeof(AB_Shotgun_Scrap_Athena_C) == 0x001358, "Wrong size on AB_Shotgun_Scrap_Athena_C");
static_assert(offsetof(AB_Shotgun_Scrap_Athena_C, UberGraphFrame_B_Shotgun_Scrap_Athena_C) == 0x001350, "Member 'AB_Shotgun_Scrap_Athena_C::UberGraphFrame_B_Shotgun_Scrap_Athena_C' has a wrong offset!");

}

