#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Base_FNCheatExt

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Base_FNCheatExt.Base_FNCheatExt_C.FNCheat_Client_SpawnActorOnServerFromView
// 0x0308 (0x0308 - 0x0000)
struct Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView final
{
public:
	class FName                                   inPackageName;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                l_loc;                                             // 0x0008(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x0048(0x0010)(ConstParm, ReferenceParm)
	class FString                                 CallFunc_Right_ReturnValue;                        // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorEyesViewPoint_OutLocation;        // 0x0068(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_GetActorEyesViewPoint_OutRotation;        // 0x0074(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0090(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x00B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x00C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x00D4(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x015C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15D[0x3];                                      // 0x015D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakVector_X;                            // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16C[0x4];                                      // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_FloatToText_ReturnValue;             // 0x0170(0x0018)()
	class FText                                   CallFunc_Conv_FloatToText_ReturnValue_1;           // 0x0188(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x01A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x01B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_FloatToText_ReturnValue_2;           // 0x01C0(0x0018)()
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x01D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x01D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1DA[0x2];                                      // 0x01DA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x01DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x01E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x01E4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x01F0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x01FC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0208(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_214[0x4];                                      // 0x0214(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0228(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0238(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x023C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0240(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0244(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0250(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25C[0x4];                                      // 0x025C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_2;          // 0x0260(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_3;              // 0x0270(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_4;              // 0x0280(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_5;              // 0x0290(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x02A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A1[0x7];                                      // 0x02A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_6;              // 0x02A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_7;              // 0x02B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_8;              // 0x02C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_9;              // 0x02D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_10;             // 0x02E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_11;             // 0x02F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView) == 0x000008, "Wrong alignment on Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView");
static_assert(sizeof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView) == 0x000308, "Wrong size on Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, inPackageName) == 0x000000, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::inPackageName' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, l_loc) == 0x000008, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::l_loc' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue) == 0x000018, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_GetPlayerController_ReturnValue) == 0x000028, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_K2_GetPawn_ReturnValue) == 0x000030, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_K2_GetPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Conv_NameToString_ReturnValue) == 0x000038, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, K2Node_MakeArray_Array) == 0x000048, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Right_ReturnValue) == 0x000058, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Right_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_GetActorEyesViewPoint_OutLocation) == 0x000068, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_GetActorEyesViewPoint_OutLocation' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_GetActorEyesViewPoint_OutRotation) == 0x000074, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_GetActorEyesViewPoint_OutRotation' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000080, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_GetForwardVector_ReturnValue) == 0x000090, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_2) == 0x0000A0, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x0000B0, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_GetPlayerController_ReturnValue_1) == 0x0000C0, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Add_VectorVector_ReturnValue) == 0x0000C8, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_LineTraceSingle_OutHit) == 0x0000D4, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_LineTraceSingle_ReturnValue) == 0x00015C, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakVector_X) == 0x000160, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakVector_Y) == 0x000164, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakVector_Z) == 0x000168, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Conv_FloatToText_ReturnValue) == 0x000170, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Conv_FloatToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Conv_FloatToText_ReturnValue_1) == 0x000188, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Conv_FloatToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Conv_TextToString_ReturnValue) == 0x0001A0, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Conv_TextToString_ReturnValue_1) == 0x0001B0, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Conv_TextToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Conv_FloatToText_ReturnValue_2) == 0x0001C0, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Conv_FloatToText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_bBlockingHit) == 0x0001D8, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_bInitialOverlap) == 0x0001D9, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_Time) == 0x0001DC, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_Distance) == 0x0001E0, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_Location) == 0x0001E4, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_ImpactPoint) == 0x0001F0, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_Normal) == 0x0001FC, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_ImpactNormal) == 0x000208, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_PhysMat) == 0x000218, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_HitActor) == 0x000220, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_HitComponent) == 0x000228, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_HitBoneName) == 0x000230, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_HitItem) == 0x000238, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_ElementIndex) == 0x00023C, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_FaceIndex) == 0x000240, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_TraceStart) == 0x000244, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_BreakHitResult_TraceEnd) == 0x000250, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Conv_TextToString_ReturnValue_2) == 0x000260, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Conv_TextToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_3) == 0x000270, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_4) == 0x000280, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_5) == 0x000290, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_IsServer_ReturnValue) == 0x0002A0, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_6) == 0x0002A8, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_7) == 0x0002B8, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_8) == 0x0002C8, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_9) == 0x0002D8, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_10) == 0x0002E8, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView, CallFunc_Concat_StrStr_ReturnValue_11) == 0x0002F8, "Member 'Base_FNCheatExt_C_FNCheat_Client_SpawnActorOnServerFromView::CallFunc_Concat_StrStr_ReturnValue_11' has a wrong offset!");

// Function Base_FNCheatExt.Base_FNCheatExt_C.FNCheat_Server_SpawnActorOnServer
// 0x0380 (0x0380 - 0x0000)
struct Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer final
{
public:
	class FName                                   inPackageName;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                InLocation;                                        // 0x0008(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   l_packageName;                                     // 0x0014(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Len_ReturnValue;                          // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           K2Node_MakeArray_Array;                            // 0x0050(0x0010)(ReferenceParm)
	struct FARFilter                              K2Node_MakeStruct_ARFilter;                        // 0x0060(0x00F0)()
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_154[0x4];                                      // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IAssetRegistry>        CallFunc_GetAssetRegistry_ReturnValue;             // 0x0158(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	TArray<struct FAssetData>                     CallFunc_GetAssets_OutAssetData;                   // 0x0168(0x0010)(ReferenceParm)
	bool                                          CallFunc_GetAssets_ReturnValue;                    // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAssetData                             CallFunc_Array_Get_Item;                           // 0x0180(0x0060)(HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x01E0(0x0030)(IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0210(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0214(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_215[0x3];                                      // 0x0215(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_NameToString_ReturnValue_1;          // 0x0218(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_229[0x7];                                      // 0x0229(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Right_ReturnValue;                        // 0x0230(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_241[0x7];                                      // 0x0241(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IAssetRegistry>        CallFunc_GetAssetRegistry_ReturnValue_1;           // 0x0248(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	TArray<struct FAssetData>                     CallFunc_GetAssetsByPackageName_OutAssetData;      // 0x0258(0x0010)(ReferenceParm)
	bool                                          CallFunc_GetAssetsByPackageName_ReturnValue;       // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0269(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_26A[0x6];                                      // 0x026A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAssetData                             CallFunc_Array_Get_Item_1;                         // 0x0270(0x0060)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x02D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D4[0x4];                                      // 0x02D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_NameToString_ReturnValue_2;          // 0x02D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E9[0x7];                                      // 0x02E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x02F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0300(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FSoftClassPath                         CallFunc_MakeSoftClassPath_ReturnValue;            // 0x0310(0x0018)(ZeroConstructor, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   CallFunc_Conv_SoftClassPathToSoftClassRef_ReturnValue; // 0x0328(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	class UClass*                                 CallFunc_LoadClassAsset_Blocking_ReturnValue;      // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class AActor>                     K2Node_ClassDynamicCast_AsActor;                   // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0360(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_361[0x7];                                      // 0x0361(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0368(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer) == 0x000010, "Wrong alignment on Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer");
static_assert(sizeof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer) == 0x000380, "Wrong size on Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, inPackageName) == 0x000000, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::inPackageName' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, InLocation) == 0x000008, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::InLocation' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, l_packageName) == 0x000014, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::l_packageName' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, Temp_bool_True_if_break_was_hit_Variable) == 0x00001C, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Conv_NameToString_ReturnValue) == 0x000020, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Len_ReturnValue) == 0x000030, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Len_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Not_PreBool_ReturnValue) == 0x000034, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, Temp_int_Loop_Counter_Variable) == 0x000038, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Add_IntInt_ReturnValue) == 0x00003C, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, Temp_int_Array_Index_Variable) == 0x000040, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_EqualEqual_NameName_ReturnValue) == 0x000044, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_EqualEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, Temp_int_Array_Index_Variable_1) == 0x000048, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, Temp_int_Loop_Counter_Variable_1) == 0x00004C, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, K2Node_MakeArray_Array) == 0x000050, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, K2Node_MakeStruct_ARFilter) == 0x000060, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::K2Node_MakeStruct_ARFilter' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Add_IntInt_ReturnValue_1) == 0x000150, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_GetAssetRegistry_ReturnValue) == 0x000158, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_GetAssetRegistry_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_GetAssets_OutAssetData) == 0x000168, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_GetAssets_OutAssetData' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_GetAssets_ReturnValue) == 0x000178, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_GetAssets_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Array_Get_Item) == 0x000180, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_MakeTransform_ReturnValue) == 0x0001E0, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Array_Length_ReturnValue) == 0x000210, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Less_IntInt_ReturnValue) == 0x000214, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Conv_NameToString_ReturnValue_1) == 0x000218, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Conv_NameToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_BooleanAND_ReturnValue) == 0x000228, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Right_ReturnValue) == 0x000230, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Right_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x000240, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_GetAssetRegistry_ReturnValue_1) == 0x000248, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_GetAssetRegistry_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_GetAssetsByPackageName_OutAssetData) == 0x000258, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_GetAssetsByPackageName_OutAssetData' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_GetAssetsByPackageName_ReturnValue) == 0x000268, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_GetAssetsByPackageName_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_IsServer_ReturnValue) == 0x000269, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Array_Get_Item_1) == 0x000270, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Array_Length_ReturnValue_1) == 0x0002D0, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Conv_NameToString_ReturnValue_2) == 0x0002D8, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Conv_NameToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Less_IntInt_ReturnValue_1) == 0x0002E8, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Concat_StrStr_ReturnValue) == 0x0002F0, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000300, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_MakeSoftClassPath_ReturnValue) == 0x000310, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_MakeSoftClassPath_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_Conv_SoftClassPathToSoftClassRef_ReturnValue) == 0x000328, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_Conv_SoftClassPathToSoftClassRef_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_LoadClassAsset_Blocking_ReturnValue) == 0x000350, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_LoadClassAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, K2Node_ClassDynamicCast_AsActor) == 0x000358, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::K2Node_ClassDynamicCast_AsActor' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, K2Node_ClassDynamicCast_bSuccess) == 0x000360, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000368, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer, CallFunc_FinishSpawningActor_ReturnValue) == 0x000370, "Member 'Base_FNCheatExt_C_FNCheat_Server_SpawnActorOnServer::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");

// Function Base_FNCheatExt.Base_FNCheatExt_C.FNCheat_SpawnKillZVisualizers
// 0x0170 (0x0170 - 0x0000)
struct Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers final
{
public:
	TSoftClassPtr<class UClass>                   BPKillVolumeVisualizer;                            // 0x0000(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   KillZVolume;                                       // 0x0028(0x0028)(Edit, BlueprintVisible, DisableEditOnTemplate, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_LoadClassAsset_Blocking_ReturnValue;      // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_LoadClassAsset_Blocking_ReturnValue_1;    // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class AKillZVolume>               K2Node_ClassDynamicCast_AsKill_ZVolume;            // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class AActor>                     K2Node_ClassDynamicCast_AsActor;                   // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess_1;                // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AKillZVolume*>                   CallFunc_GetAllActorsOfClass_OutActors;            // 0x0090(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AKillZVolume*                           CallFunc_Array_Get_Item;                           // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x3];                                       // 0x00B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetComponentBounds_Origin;                // 0x00B4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetComponentBounds_BoxExtent;             // 0x00C0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetComponentBounds_SphereRadius;          // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x00D0(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0100(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x010C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x0118(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0124(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0130(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers) == 0x000010, "Wrong alignment on Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers");
static_assert(sizeof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers) == 0x000170, "Wrong size on Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, BPKillVolumeVisualizer) == 0x000000, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::BPKillVolumeVisualizer' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, KillZVolume) == 0x000028, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::KillZVolume' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, Temp_int_Array_Index_Variable) == 0x000050, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, Temp_int_Loop_Counter_Variable) == 0x000054, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_Add_IntInt_ReturnValue) == 0x000058, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_LoadClassAsset_Blocking_ReturnValue) == 0x000060, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_LoadClassAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_LoadClassAsset_Blocking_ReturnValue_1) == 0x000068, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_LoadClassAsset_Blocking_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, K2Node_ClassDynamicCast_AsKill_ZVolume) == 0x000070, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::K2Node_ClassDynamicCast_AsKill_ZVolume' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, K2Node_ClassDynamicCast_bSuccess) == 0x000078, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, K2Node_ClassDynamicCast_AsActor) == 0x000080, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::K2Node_ClassDynamicCast_AsActor' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, K2Node_ClassDynamicCast_bSuccess_1) == 0x000088, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::K2Node_ClassDynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_GetAllActorsOfClass_OutActors) == 0x000090, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_Array_Length_ReturnValue) == 0x0000A0, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_Array_Get_Item) == 0x0000A8, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_Less_IntInt_ReturnValue) == 0x0000B0, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_GetComponentBounds_Origin) == 0x0000B4, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_GetComponentBounds_Origin' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_GetComponentBounds_BoxExtent) == 0x0000C0, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_GetComponentBounds_BoxExtent' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_GetComponentBounds_SphereRadius) == 0x0000CC, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_GetComponentBounds_SphereRadius' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_GetTransform_ReturnValue) == 0x0000D0, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000100, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_BreakTransform_Location) == 0x00010C, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_BreakTransform_Rotation) == 0x000118, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_BreakTransform_Scale) == 0x000124, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_MakeTransform_ReturnValue) == 0x000130, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000160, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers, CallFunc_FinishSpawningActor_ReturnValue) == 0x000168, "Member 'Base_FNCheatExt_C_FNCheat_SpawnKillZVisualizers::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");

// Function Base_FNCheatExt.Base_FNCheatExt_C.FNCheat_ClearKillZVisualizers
// 0x0078 (0x0078 - 0x0000)
struct Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers final
{
public:
	TSoftClassPtr<class UClass>                   BPKillVolumeVisualizer;                            // 0x0000(0x0028)(Edit, BlueprintVisible, DisableEditOnTemplate, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_LoadClassAsset_Blocking_ReturnValue;      // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSubclassOf<class AActor>                     K2Node_ClassDynamicCast_AsActor;                   // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_GetAllActorsOfClass_OutActors;            // 0x0050(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers) == 0x000008, "Wrong alignment on Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers");
static_assert(sizeof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers) == 0x000078, "Wrong size on Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, BPKillVolumeVisualizer) == 0x000000, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::BPKillVolumeVisualizer' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, Temp_int_Array_Index_Variable) == 0x000028, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, Temp_int_Loop_Counter_Variable) == 0x00002C, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, CallFunc_Add_IntInt_ReturnValue) == 0x000030, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, CallFunc_LoadClassAsset_Blocking_ReturnValue) == 0x000038, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::CallFunc_LoadClassAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, K2Node_ClassDynamicCast_AsActor) == 0x000040, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::K2Node_ClassDynamicCast_AsActor' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, K2Node_ClassDynamicCast_bSuccess) == 0x000048, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::K2Node_ClassDynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, CallFunc_GetAllActorsOfClass_OutActors) == 0x000050, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, CallFunc_Array_Length_ReturnValue) == 0x000060, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, CallFunc_Array_Get_Item) == 0x000068, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers, CallFunc_Less_IntInt_ReturnValue) == 0x000070, "Member 'Base_FNCheatExt_C_FNCheat_ClearKillZVisualizers::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

}

