#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePassBase

#include "Basic.hpp"


namespace SDK
{

// Enum BattlePassBase.BattlePassTileAvailabilityStates
// NumValues: 0x0005
enum class EBattlePassTileAvailabilityStates : uint8
{
	Invalid                                  = 0,
	Available                                = 1,
	Owned                                    = 2,
	Locked                                   = 3,
	BattlePassTileAvailabilityStates_MAX     = 4,
};

}

