#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BGA_Bow_Stink_Cloud_Athena

#include "Basic.hpp"

#include "BGA_Bow_Stink_Cloud_Athena_classes.hpp"
#include "BGA_Bow_Stink_Cloud_Athena_parameters.hpp"


namespace SDK
{

// Function BGA_Bow_Stink_Cloud_Athena.BGA_Bow_Stink_Cloud_Athena_C.ExecuteUbergraph_BGA_Bow_Stink_Cloud_Athena
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Bow_Stink_Cloud_Athena_C::ExecuteUbergraph_BGA_Bow_Stink_Cloud_Athena(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Bow_Stink_Cloud_Athena_C", "ExecuteUbergraph_BGA_Bow_Stink_Cloud_Athena");

	Params::BGA_Bow_Stink_Cloud_Athena_C_ExecuteUbergraph_BGA_Bow_Stink_Cloud_Athena Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Bow_Stink_Cloud_Athena.BGA_Bow_Stink_Cloud_Athena_C.FadeOut
// (BlueprintCallable, BlueprintEvent)

void ABGA_Bow_Stink_Cloud_Athena_C::FadeOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Bow_Stink_Cloud_Athena_C", "FadeOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Bow_Stink_Cloud_Athena.BGA_Bow_Stink_Cloud_Athena_C.FadeIn
// (BlueprintCallable, BlueprintEvent)

void ABGA_Bow_Stink_Cloud_Athena_C::FadeIn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Bow_Stink_Cloud_Athena_C", "FadeIn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Bow_Stink_Cloud_Athena.BGA_Bow_Stink_Cloud_Athena_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABGA_Bow_Stink_Cloud_Athena_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Bow_Stink_Cloud_Athena_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Bow_Stink_Cloud_Athena.BGA_Bow_Stink_Cloud_Athena_C.HideAndKill
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABGA_Bow_Stink_Cloud_Athena_C::HideAndKill()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Bow_Stink_Cloud_Athena_C", "HideAndKill");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Bow_Stink_Cloud_Athena.BGA_Bow_Stink_Cloud_Athena_C.FadeSmokeTL__UpdateFunc
// (BlueprintEvent)

void ABGA_Bow_Stink_Cloud_Athena_C::FadeSmokeTL__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Bow_Stink_Cloud_Athena_C", "FadeSmokeTL__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Bow_Stink_Cloud_Athena.BGA_Bow_Stink_Cloud_Athena_C.FadeSmokeTL__FinishedFunc
// (BlueprintEvent)

void ABGA_Bow_Stink_Cloud_Athena_C::FadeSmokeTL__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Bow_Stink_Cloud_Athena_C", "FadeSmokeTL__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Bow_Stink_Cloud_Athena.BGA_Bow_Stink_Cloud_Athena_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABGA_Bow_Stink_Cloud_Athena_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Bow_Stink_Cloud_Athena_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

