#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RealityWaveManager

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "MovieScene_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_RealityWaveManager.BP_RealityWaveManager_C.ExecuteUbergraph_BP_RealityWaveManager
// 0x01E0 (0x01E0 - 0x0000)
struct BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class ALevelSequenceActor>     CallFunc_Array_Get_Item;                           // 0x0018(0x0028)(HasGetValueTypeHash)
	TDelegate<void(class AFortGameStateAthena* GameState, class UFortPlaylist* Playlist, struct FGameplayTagContainer& PlaylistContextTags)> K2Node_CreateDelegate_OutputDelegate;              // 0x0040(0x0010)(ZeroConstructor, NoDestructor)
	class UObject*                                CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue; // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ALevelSequenceActor*                    K2Node_DynamicCast_AsLevel_Sequence_Actor;         // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         K2Node_CustomEvent_targets;                        // 0x0068(0x0010)(ConstParm, ReferenceParm)
	int32                                         K2Node_CustomEvent_WaveID;                         // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_GetAllActorsWithTag_OutActors;            // 0x0080(0x0010)(ReferenceParm)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0098(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x00A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	uint8                                         Pad_B8[0x8];                                       // 0x00B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x00C0(0x0030)(IsPlainOldData, NoDestructor)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_RealityWave_C*                      CallFunc_FinishSpawningActor_ReturnValue;          // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_112[0x6];                                      // 0x0112(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortAsyncAction_CurrentPlaylistReady*  CallFunc_PlaylistDataReadyAsync_ReturnValue;       // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortGameStateAthena*                   Temp_object_Variable;                              // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_129[0x7];                                      // 0x0129(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortPlaylist*                          Temp_object_Variable_1;                            // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  Temp_struct_Variable;                              // 0x0138(0x0020)()
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_159[0x7];                                      // 0x0159(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ALevelSequenceActor*                    CallFunc_Array_Get_Item_1;                         // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULevelSequencePlayer*                   CallFunc_GetSequencePlayer_ReturnValue;            // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_171[0x3];                                      // 0x0171(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FQualifiedFrameTime                    CallFunc_GetStartTime_ReturnValue;                 // 0x0174(0x0010)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_QualifiedFrameTimeToSeconds_ReturnValue; // 0x0184(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMovieSceneSequencePlaybackParams      K2Node_MakeStruct_MovieSceneSequencePlaybackParams; // 0x0188(0x0028)()
	class AFortGameStateAthena*                   K2Node_CustomEvent_GameState;                      // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UFortPlaylist*                    K2Node_CustomEvent_Playlist;                       // 0x01B8(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  K2Node_CustomEvent_PlaylistContextTags;            // 0x01C0(0x0020)(ConstParm)
};
static_assert(alignof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager) == 0x000010, "Wrong alignment on BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager");
static_assert(sizeof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager) == 0x0001E0, "Wrong size on BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, EntryPoint) == 0x000000, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Array_Length_ReturnValue) == 0x000008, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Less_IntInt_ReturnValue) == 0x000010, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, Temp_int_Array_Index_Variable) == 0x000014, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Array_Get_Item) == 0x000018, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, K2Node_CreateDelegate_OutputDelegate) == 0x000040, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue) == 0x000050, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, K2Node_DynamicCast_AsLevel_Sequence_Actor) == 0x000058, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::K2Node_DynamicCast_AsLevel_Sequence_Actor' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, K2Node_DynamicCast_bSuccess) == 0x000060, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, K2Node_CustomEvent_targets) == 0x000068, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::K2Node_CustomEvent_targets' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, K2Node_CustomEvent_WaveID) == 0x000078, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::K2Node_CustomEvent_WaveID' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_GetAllActorsWithTag_OutActors) == 0x000080, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_GetAllActorsWithTag_OutActors' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000090, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Conv_IntToString_ReturnValue) == 0x000098, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Concat_StrStr_ReturnValue) == 0x0000A8, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_MakeTransform_ReturnValue) == 0x0000C0, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Conv_StringToName_ReturnValue) == 0x0000F0, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0000F8, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_FinishSpawningActor_ReturnValue) == 0x000100, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, Temp_int_Variable) == 0x000108, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Add_IntInt_ReturnValue_1) == 0x00010C, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_HasAuthority_ReturnValue) == 0x000110, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_IsDedicatedServer_ReturnValue) == 0x000111, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_PlaylistDataReadyAsync_ReturnValue) == 0x000118, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_PlaylistDataReadyAsync_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, Temp_object_Variable) == 0x000120, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_IsValid_ReturnValue) == 0x000128, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, Temp_object_Variable_1) == 0x000130, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, Temp_struct_Variable) == 0x000138, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000158, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Array_Get_Item_1) == 0x000160, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_GetSequencePlayer_ReturnValue) == 0x000168, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_GetSequencePlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_IsValid_ReturnValue_1) == 0x000170, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_GetStartTime_ReturnValue) == 0x000174, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_GetStartTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, CallFunc_Conv_QualifiedFrameTimeToSeconds_ReturnValue) == 0x000184, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::CallFunc_Conv_QualifiedFrameTimeToSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, K2Node_MakeStruct_MovieSceneSequencePlaybackParams) == 0x000188, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::K2Node_MakeStruct_MovieSceneSequencePlaybackParams' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, K2Node_CustomEvent_GameState) == 0x0001B0, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::K2Node_CustomEvent_GameState' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, K2Node_CustomEvent_Playlist) == 0x0001B8, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::K2Node_CustomEvent_Playlist' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager, K2Node_CustomEvent_PlaylistContextTags) == 0x0001C0, "Member 'BP_RealityWaveManager_C_ExecuteUbergraph_BP_RealityWaveManager::K2Node_CustomEvent_PlaylistContextTags' has a wrong offset!");

// Function BP_RealityWaveManager.BP_RealityWaveManager_C.TriggerWave
// 0x0004 (0x0004 - 0x0000)
struct BP_RealityWaveManager_C_TriggerWave final
{
public:
	int32                                         WaveID;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RealityWaveManager_C_TriggerWave) == 0x000004, "Wrong alignment on BP_RealityWaveManager_C_TriggerWave");
static_assert(sizeof(BP_RealityWaveManager_C_TriggerWave) == 0x000004, "Wrong size on BP_RealityWaveManager_C_TriggerWave");
static_assert(offsetof(BP_RealityWaveManager_C_TriggerWave, WaveID) == 0x000000, "Member 'BP_RealityWaveManager_C_TriggerWave::WaveID' has a wrong offset!");

// Function BP_RealityWaveManager.BP_RealityWaveManager_C.SpawnWave
// 0x0010 (0x0010 - 0x0000)
struct BP_RealityWaveManager_C_SpawnWave final
{
public:
	TArray<class AActor*>                         Targets;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BP_RealityWaveManager_C_SpawnWave) == 0x000008, "Wrong alignment on BP_RealityWaveManager_C_SpawnWave");
static_assert(sizeof(BP_RealityWaveManager_C_SpawnWave) == 0x000010, "Wrong size on BP_RealityWaveManager_C_SpawnWave");
static_assert(offsetof(BP_RealityWaveManager_C_SpawnWave, Targets) == 0x000000, "Member 'BP_RealityWaveManager_C_SpawnWave::Targets' has a wrong offset!");

// Function BP_RealityWaveManager.BP_RealityWaveManager_C.OnReady_A0A316114D6599BF6DE0229F0ADB7D55
// 0x0030 (0x0030 - 0x0000)
struct BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55 final
{
public:
	class AFortGameStateAthena*                   GameState;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UFortPlaylist*                    Playlist;                                          // 0x0008(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  PlaylistContextTags;                               // 0x0010(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55) == 0x000008, "Wrong alignment on BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55");
static_assert(sizeof(BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55) == 0x000030, "Wrong size on BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55");
static_assert(offsetof(BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55, GameState) == 0x000000, "Member 'BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55::GameState' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55, Playlist) == 0x000008, "Member 'BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55::Playlist' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55, PlaylistContextTags) == 0x000010, "Member 'BP_RealityWaveManager_C_OnReady_A0A316114D6599BF6DE0229F0ADB7D55::PlaylistContextTags' has a wrong offset!");

// Function BP_RealityWaveManager.BP_RealityWaveManager_C.UpdateYogurtTODM
// 0x0010 (0x0010 - 0x0000)
struct BP_RealityWaveManager_C_UpdateYogurtTODM final
{
public:
	class ABP_Yogurt_TODM_Standalone_C*           CallFunc_GetYogurtTODM_Output_Get;                 // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_RealityWaveManager_C_UpdateYogurtTODM) == 0x000008, "Wrong alignment on BP_RealityWaveManager_C_UpdateYogurtTODM");
static_assert(sizeof(BP_RealityWaveManager_C_UpdateYogurtTODM) == 0x000010, "Wrong size on BP_RealityWaveManager_C_UpdateYogurtTODM");
static_assert(offsetof(BP_RealityWaveManager_C_UpdateYogurtTODM, CallFunc_GetYogurtTODM_Output_Get) == 0x000000, "Member 'BP_RealityWaveManager_C_UpdateYogurtTODM::CallFunc_GetYogurtTODM_Output_Get' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_UpdateYogurtTODM, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'BP_RealityWaveManager_C_UpdateYogurtTODM::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_RealityWaveManager.BP_RealityWaveManager_C.GetYogurtTODM
// 0x0028 (0x0028 - 0x0000)
struct BP_RealityWaveManager_C_GetYogurtTODM final
{
public:
	class ABP_Yogurt_TODM_Standalone_C*           Output_Get;                                        // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABP_Yogurt_TODM_Standalone_C*>   CallFunc_GetAllActorsOfClass_OutActors;            // 0x0010(0x0010)(ReferenceParm)
	class ABP_Yogurt_TODM_Standalone_C*           CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_RealityWaveManager_C_GetYogurtTODM) == 0x000008, "Wrong alignment on BP_RealityWaveManager_C_GetYogurtTODM");
static_assert(sizeof(BP_RealityWaveManager_C_GetYogurtTODM) == 0x000028, "Wrong size on BP_RealityWaveManager_C_GetYogurtTODM");
static_assert(offsetof(BP_RealityWaveManager_C_GetYogurtTODM, Output_Get) == 0x000000, "Member 'BP_RealityWaveManager_C_GetYogurtTODM::Output_Get' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_GetYogurtTODM, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'BP_RealityWaveManager_C_GetYogurtTODM::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_GetYogurtTODM, CallFunc_GetAllActorsOfClass_OutActors) == 0x000010, "Member 'BP_RealityWaveManager_C_GetYogurtTODM::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(BP_RealityWaveManager_C_GetYogurtTODM, CallFunc_Array_Get_Item) == 0x000020, "Member 'BP_RealityWaveManager_C_GetYogurtTODM::CallFunc_Array_Get_Item' has a wrong offset!");

}

