#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Yogurt_Scripting

#include "Basic.hpp"

#include "BP_Yogurt_Scripting_classes.hpp"
#include "BP_Yogurt_Scripting_parameters.hpp"


namespace SDK
{

// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ExecuteUbergraph_BP_Yogurt_Scripting
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ExecuteUbergraph_BP_Yogurt_Scripting(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ExecuteUbergraph_BP_Yogurt_Scripting");

	Params::BP_Yogurt_Scripting_C_ExecuteUbergraph_BP_Yogurt_Scripting Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ApplyJonesyCollisionKnockback
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   JonesyCollisionYaw                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ApplyJonesyCollisionKnockback(int32 JonesyCollisionYaw)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ApplyJonesyCollisionKnockback");

	Params::BP_Yogurt_Scripting_C_ApplyJonesyCollisionKnockback Parms{};

	Parms.JonesyCollisionYaw = JonesyCollisionYaw;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnIntroBoundaryTriggered
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::OnIntroBoundaryTriggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnIntroBoundaryTriggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnTowerBoundaryTriggered
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::OnTowerBoundaryTriggered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnTowerBoundaryTriggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ForceTeleportEffect
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ForceTeleportEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ForceTeleportEffect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.CE_EnvironmentDustEnd
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::CE_EnvironmentDustEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "CE_EnvironmentDustEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.CE_EnvironmentDustStart
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::CE_EnvironmentDustStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "CE_EnvironmentDustStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PlayShakeFromSequencer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Shake_Magnitude                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Shake_Size                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::PlayShakeFromSequencer(float Shake_Magnitude, int32 Shake_Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PlayShakeFromSequencer");

	Params::BP_Yogurt_Scripting_C_PlayShakeFromSequencer Parms{};

	Parms.Shake_Magnitude = Shake_Magnitude;
	Parms.Shake_Size = Shake_Size;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.TriggerEnvironmentalKnockback
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CallSwitchEventTrigger                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::TriggerEnvironmentalKnockback(int32 CallSwitchEventTrigger)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "TriggerEnvironmentalKnockback");

	Params::BP_Yogurt_Scripting_C_TriggerEnvironmentalKnockback Parms{};

	Parms.CallSwitchEventTrigger = CallSwitchEventTrigger;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.KnockPlayerFromZP
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AController*                      Controller                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::KnockPlayerFromZP(class AController* Controller)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "KnockPlayerFromZP");

	Params::BP_Yogurt_Scripting_C_KnockPlayerFromZP Parms{};

	Parms.Controller = Controller;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.JFly_To_Jonsey_Transition_FX
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::JFly_To_Jonsey_Transition_FX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "JFly_To_Jonsey_Transition_FX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnMainVOSequencesPlay
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::OnMainVOSequencesPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnMainVOSequencesPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnJonesyFlyWantsToTalk
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EBP_Enum_Yogurt_DynamicVOCallouts_Types CalloutType                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::OnJonesyFlyWantsToTalk(EBP_Enum_Yogurt_DynamicVOCallouts_Types CalloutType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnJonesyFlyWantsToTalk");

	Params::BP_Yogurt_Scripting_C_OnJonesyFlyWantsToTalk Parms{};

	Parms.CalloutType = CalloutType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SetJonesyPortalVisible
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    JonesyPortalVisible                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Yogurt_Scripting_C::SetJonesyPortalVisible(bool JonesyPortalVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SetJonesyPortalVisible");

	Params::BP_Yogurt_Scripting_C_SetJonesyPortalVisible Parms{};

	Parms.JonesyPortalVisible = JonesyPortalVisible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PortalApplyKnockback
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Yogurt_Portal_C*              PortalCollidedWith                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::PortalApplyKnockback(class ABP_Yogurt_Portal_C* PortalCollidedWith)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PortalApplyKnockback");

	Params::BP_Yogurt_Scripting_C_PortalApplyKnockback Parms{};

	Parms.PortalCollidedWith = PortalCollidedWith;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SetupVortexEvents
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::SetupVortexEvents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SetupVortexEvents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.Client_OnPawnLandedOnTower
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::Client_OnPawnLandedOnTower()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "Client_OnPawnLandedOnTower");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.Client_OnPawnEnteredZeroPointVortex
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::Client_OnPawnEnteredZeroPointVortex()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "Client_OnPawnEnteredZeroPointVortex");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.IntroCine_SetPlayerVisibility
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsVisible                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Yogurt_Scripting_C::IntroCine_SetPlayerVisibility(bool bIsVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "IntroCine_SetPlayerVisibility");

	Params::BP_Yogurt_Scripting_C_IntroCine_SetPlayerVisibility Parms{};

	Parms.bIsVisible = bIsVisible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.FlowerIsTurningRed
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::FlowerIsTurningRed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "FlowerIsTurningRed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.Initialize Combat FX
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::Initialize_Combat_FX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "Initialize Combat FX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnNewPhasePortalSequencesStarted
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LocalEventPhase_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::OnNewPhasePortalSequencesStarted(int32 LocalEventPhase_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnNewPhasePortalSequencesStarted");

	Params::BP_Yogurt_Scripting_C_OnNewPhasePortalSequencesStarted Parms{};

	Parms.LocalEventPhase_0 = LocalEventPhase_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.InitLocalPhasePortalSequences
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::InitLocalPhasePortalSequences()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "InitLocalPhasePortalSequences");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SetTowerBoundaryActive
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::SetTowerBoundaryActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SetTowerBoundaryActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ClientRequestCosmeticSwap_Four
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ClientRequestCosmeticSwap_Four()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ClientRequestCosmeticSwap_Four");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ChangePawnSkinEvent_Four
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ChangePawnSkinEvent_Four(class AFortPlayerControllerAthena* PC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ChangePawnSkinEvent_Four");

	Params::BP_Yogurt_Scripting_C_ChangePawnSkinEvent_Four Parms{};

	Parms.PC = PC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.TeleportCharge_Stage_1
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::TeleportCharge_Stage_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "TeleportCharge_Stage_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.GameplayOutroStarted
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      PlayerControllerAthena                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::GameplayOutroStarted(class AFortPlayerControllerAthena* PlayerControllerAthena)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "GameplayOutroStarted");

	Params::BP_Yogurt_Scripting_C_GameplayOutroStarted Parms{};

	Parms.PlayerControllerAthena = PlayerControllerAthena;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PreloadFirstLocation
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::PreloadFirstLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PreloadFirstLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ClearCurrentExtraViewpoint
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ClearCurrentExtraViewpoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ClearCurrentExtraViewpoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PreloadNextTeleportLocation
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::PreloadNextTeleportLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PreloadNextTeleportLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.TeleportPawnToFallBackPosition
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PortalNum                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::TeleportPawnToFallBackPosition(class AFortPlayerControllerAthena* PC, int32 PortalNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "TeleportPawnToFallBackPosition");

	Params::BP_Yogurt_Scripting_C_TeleportPawnToFallBackPosition Parms{};

	Parms.PC = PC;
	Parms.PortalNum = PortalNum;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnClientPickupPortalDeviceSpawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_PortalCloser_Pickup_C*        portal_device_pickup                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::OnClientPickupPortalDeviceSpawned(class ABP_PortalCloser_Pickup_C* portal_device_pickup)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnClientPickupPortalDeviceSpawned");

	Params::BP_Yogurt_Scripting_C_OnClientPickupPortalDeviceSpawned Parms{};

	Parms.portal_device_pickup = portal_device_pickup;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.CE_UpdraftEnd
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::CE_UpdraftEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "CE_UpdraftEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.CE_UpdraftStart
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::CE_UpdraftStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "CE_UpdraftStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PlayMasterAtFrame
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Playback_Frame                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::PlayMasterAtFrame(float Playback_Frame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PlayMasterAtFrame");

	Params::BP_Yogurt_Scripting_C_PlayMasterAtFrame Parms{};

	Parms.Playback_Frame = Playback_Frame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.startevent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LocalEventPhase_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::startevent(int32 LocalEventPhase_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "startevent");

	Params::BP_Yogurt_Scripting_C_startevent Parms{};

	Parms.LocalEventPhase_0 = LocalEventPhase_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ChangePawnSkinEvent_Three
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ChangePawnSkinEvent_Three(class AFortPlayerControllerAthena* PC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ChangePawnSkinEvent_Three");

	Params::BP_Yogurt_Scripting_C_ChangePawnSkinEvent_Three Parms{};

	Parms.PC = PC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ClientRequestCosmeticSwap_Three
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ClientRequestCosmeticSwap_Three()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ClientRequestCosmeticSwap_Three");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ChangePawnSkinEvent_Two
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ChangePawnSkinEvent_Two(class AFortPlayerControllerAthena* PC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ChangePawnSkinEvent_Two");

	Params::BP_Yogurt_Scripting_C_ChangePawnSkinEvent_Two Parms{};

	Parms.PC = PC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ClientPawnHitByRealityWave
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NumWaveHits                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   WaveID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ClientPawnHitByRealityWave(int32 NumWaveHits, int32 WaveID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ClientPawnHitByRealityWave");

	Params::BP_Yogurt_Scripting_C_ClientPawnHitByRealityWave Parms{};

	Parms.NumWaveHits = NumWaveHits;
	Parms.WaveID = WaveID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ClientRequestCosmeticSwap_Two
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ClientRequestCosmeticSwap_Two()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ClientRequestCosmeticSwap_Two");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SetupFirstPawnRealityWave
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::SetupFirstPawnRealityWave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SetupFirstPawnRealityWave");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ClientRequestCosmeticSwap_One
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ClientRequestCosmeticSwap_One()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ClientRequestCosmeticSwap_One");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ResetCharacterCosmetics
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ResetCharacterCosmetics(class AFortPlayerControllerAthena* PC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ResetCharacterCosmetics");

	Params::BP_Yogurt_Scripting_C_ResetCharacterCosmetics Parms{};

	Parms.PC = PC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SpecialEventCallSwitch
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::SpecialEventCallSwitch(class AFortPlayerControllerAthena* PC, int32 Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SpecialEventCallSwitch");

	Params::BP_Yogurt_Scripting_C_SpecialEventCallSwitch Parms{};

	Parms.PC = PC;
	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ClientRequestResetCosmetics
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ClientRequestResetCosmetics()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ClientRequestResetCosmetics");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ChangePawnSkinEvent_One
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ChangePawnSkinEvent_One(class AFortPlayerControllerAthena* PC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ChangePawnSkinEvent_One");

	Params::BP_Yogurt_Scripting_C_ChangePawnSkinEvent_One Parms{};

	Parms.PC = PC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.LaunchPlayerFromGroundIntoVortex
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::LaunchPlayerFromGroundIntoVortex()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "LaunchPlayerFromGroundIntoVortex");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.LaunchPlayerFromTopOfTower
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::LaunchPlayerFromTopOfTower()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "LaunchPlayerFromTopOfTower");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.InitController_Ready
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      NewPlayer                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::InitController_Ready(class AFortPlayerControllerAthena* NewPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "InitController_Ready");

	Params::BP_Yogurt_Scripting_C_InitController_Ready Parms{};

	Parms.NewPlayer = NewPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PlayBPTrailer
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::PlayBPTrailer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PlayBPTrailer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.DespawnJfly
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::DespawnJfly()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "DespawnJfly");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ResumeFinalSequence
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ResumeFinalSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ResumeFinalSequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PauseFinalSequence
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::PauseFinalSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PauseFinalSequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PlayFinalSequence
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::PlayFinalSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PlayFinalSequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PlayLastPortalSequence
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::PlayLastPortalSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PlayLastPortalSequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ResumeMasterSequence
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ResumeMasterSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ResumeMasterSequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.IntroCineFinished
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      PlayerControllerAthena                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::IntroCineFinished(class AFortPlayerControllerAthena* PlayerControllerAthena)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "IntroCineFinished");

	Params::BP_Yogurt_Scripting_C_IntroCineFinished Parms{};

	Parms.PlayerControllerAthena = PlayerControllerAthena;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.GrantPortalDevice
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::GrantPortalDevice()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "GrantPortalDevice");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.RevealGameplayPortals
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::RevealGameplayPortals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "RevealGameplayPortals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.TeleportToPhaseLocation
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::TeleportToPhaseLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "TeleportToPhaseLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PauseMasterSequence
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::PauseMasterSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PauseMasterSequence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.JFlyReveal
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::JFlyReveal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "JFlyReveal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SpawnJFly
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::SpawnJFly()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SpawnJFly");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PlayerOutOfEventBounds
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::PlayerOutOfEventBounds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PlayerOutOfEventBounds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.HandlePortalsForPhase
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LocalPhase                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::HandlePortalsForPhase(int32 LocalPhase)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "HandlePortalsForPhase");

	Params::BP_Yogurt_Scripting_C_HandlePortalsForPhase Parms{};

	Parms.LocalPhase = LocalPhase;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnPortalClosed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Yogurt_Portal_C*              ClosedPortal                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::OnPortalClosed(class ABP_Yogurt_Portal_C* ClosedPortal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnPortalClosed");

	Params::BP_Yogurt_Scripting_C_OnPortalClosed Parms{};

	Parms.ClosedPortal = ClosedPortal;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.GivePlayerBackMovement
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::GivePlayerBackMovement()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "GivePlayerBackMovement");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ClientAskingToProgress
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSpecialClientEvent              ClientEventData                                        (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void ABP_Yogurt_Scripting_C::ClientAskingToProgress(const struct FSpecialClientEvent& ClientEventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ClientAskingToProgress");

	Params::BP_Yogurt_Scripting_C_ClientAskingToProgress Parms{};

	Parms.ClientEventData = std::move(ClientEventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnPawnLoaded_SetState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerPawnAthena*            NewPawn                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::OnPawnLoaded_SetState(class AFortPlayerPawnAthena* NewPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnPawnLoaded_SetState");

	Params::BP_Yogurt_Scripting_C_OnPawnLoaded_SetState Parms{};

	Parms.NewPawn = NewPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ProgressPhase
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ProgressPhase()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ProgressPhase");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PlaySequence
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ALevelSequenceActor*              SequenceToPlay                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::PlaySequence(class ALevelSequenceActor* SequenceToPlay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PlaySequence");

	Params::BP_Yogurt_Scripting_C_PlaySequence Parms{};

	Parms.SequenceToPlay = SequenceToPlay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.InvincibilityMutator
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::InvincibilityMutator()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "InvincibilityMutator");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.EnableTheMutator
// (BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::EnableTheMutator()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "EnableTheMutator");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Yogurt_Scripting_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnReady_557CEFBA49484CDDF58828B65A79B523
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortControllerComponent_GameplayCinematic*FoundComponent                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::OnReady_557CEFBA49484CDDF58828B65A79B523(class UFortControllerComponent_GameplayCinematic* FoundComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnReady_557CEFBA49484CDDF58828B65A79B523");

	Params::BP_Yogurt_Scripting_C_OnReady_557CEFBA49484CDDF58828B65A79B523 Parms{};

	Parms.FoundComponent = FoundComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnReady_A830C407494FB0C8F10E8987FF9C8C98
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortControllerComponent_GameplayCinematic*FoundComponent                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::OnReady_A830C407494FB0C8F10E8987FF9C8C98(class UFortControllerComponent_GameplayCinematic* FoundComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnReady_A830C407494FB0C8F10E8987FF9C8C98");

	Params::BP_Yogurt_Scripting_C_OnReady_A830C407494FB0C8F10E8987FF9C8C98 Parms{};

	Parms.FoundComponent = FoundComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.OnReady_F6E6B09F4E6AA115465FAABCD4B97504
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortGameStateAthena*             GameState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortPlaylist*                    Playlist                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            PlaylistContextTags                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_Yogurt_Scripting_C::OnReady_F6E6B09F4E6AA115465FAABCD4B97504(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "OnReady_F6E6B09F4E6AA115465FAABCD4B97504");

	Params::BP_Yogurt_Scripting_C_OnReady_F6E6B09F4E6AA115465FAABCD4B97504 Parms{};

	Parms.GameState = GameState;
	Parms.Playlist = Playlist;
	Parms.PlaylistContextTags = std::move(PlaylistContextTags);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.InitClientPortals
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::InitClientPortals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "InitClientPortals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.GetPortalForLocalPhase
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Phase                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_Yogurt_Portal_C*              Portal                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::GetPortalForLocalPhase(int32 Phase, class ABP_Yogurt_Portal_C** Portal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "GetPortalForLocalPhase");

	Params::BP_Yogurt_Scripting_C_GetPortalForLocalPhase Parms{};

	Parms.Phase = Phase;

	UObject::ProcessEvent(Func, &Parms);

	if (Portal != nullptr)
		*Portal = Parms.Portal;
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.UpdateJFlyWithCurrentObjective
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::UpdateJFlyWithCurrentObjective()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "UpdateJFlyWithCurrentObjective");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.Init Portal Teleport Transforms
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::Init_Portal_Teleport_Transforms()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "Init Portal Teleport Transforms");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SwitchToSpecialScriptEvents
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::SwitchToSpecialScriptEvents(int32 Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SwitchToSpecialScriptEvents");

	Params::BP_Yogurt_Scripting_C_SwitchToSpecialScriptEvents Parms{};

	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SwapCharacterParts
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AFortPlayerControllerAthena*      PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::SwapCharacterParts(int32 Index_0, class AFortPlayerControllerAthena* PC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SwapCharacterParts");

	Params::BP_Yogurt_Scripting_C_SwapCharacterParts Parms{};

	Parms.Index_0 = Index_0;
	Parms.PC = PC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ChangePawnRealityWaveTargetID
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   newWaveID                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ChangePawnRealityWaveTargetID(int32 newWaveID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ChangePawnRealityWaveTargetID");

	Params::BP_Yogurt_Scripting_C_ChangePawnRealityWaveTargetID Parms{};

	Parms.newWaveID = newWaveID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.UpdateVisualsTODM
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EBP_Enum_Yogurt_TODM_States             TODM_State                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IgnoreSettingSkyMaterial                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Yogurt_Scripting_C::UpdateVisualsTODM(EBP_Enum_Yogurt_TODM_States TODM_State, bool IgnoreSettingSkyMaterial)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "UpdateVisualsTODM");

	Params::BP_Yogurt_Scripting_C_UpdateVisualsTODM Parms{};

	Parms.TODM_State = TODM_State;
	Parms.IgnoreSettingSkyMaterial = IgnoreSettingSkyMaterial;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.InitClientTODMReference
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::InitClientTODMReference()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "InitClientTODMReference");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.CallPortalClosedTODM
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Stage                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::CallPortalClosedTODM(int32 Stage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "CallPortalClosedTODM");

	Params::BP_Yogurt_Scripting_C_CallPortalClosedTODM Parms{};

	Parms.Stage = Stage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SetupDynamicVOCallouts
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::SetupDynamicVOCallouts()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SetupDynamicVOCallouts");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.IsAnyVOSequencePlaying
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bIsAnythingPlaying                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Yogurt_Scripting_C::IsAnyVOSequencePlaying(bool* bIsAnythingPlaying)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "IsAnyVOSequencePlaying");

	Params::BP_Yogurt_Scripting_C_IsAnyVOSequencePlaying Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bIsAnythingPlaying != nullptr)
		*bIsAnythingPlaying = Parms.bIsAnythingPlaying;
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ApplyPortalKnockback
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       TriggeringPlayerPawn                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TSoftObjectPtr<class ABP_Yogurt_Portal_C>TriggeredPortal                                        (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
// struct FVector                          TriggeredPortalKnockback                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ApplyPortalKnockback(class ACharacter* TriggeringPlayerPawn, TSoftObjectPtr<class ABP_Yogurt_Portal_C> TriggeredPortal, const struct FVector& TriggeredPortalKnockback)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ApplyPortalKnockback");

	Params::BP_Yogurt_Scripting_C_ApplyPortalKnockback Parms{};

	Parms.TriggeringPlayerPawn = TriggeringPlayerPawn;
	Parms.TriggeredPortal = TriggeredPortal;
	Parms.TriggeredPortalKnockback = std::move(TriggeredPortalKnockback);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.Get Next Array Item
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class USoundCue*>                Array                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class USoundCue*                        PreviousArrayItem                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USoundCue*                        RandomArrayItem                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::Get_Next_Array_Item(TArray<class USoundCue*>& Array, class USoundCue* PreviousArrayItem, class USoundCue** RandomArrayItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "Get Next Array Item");

	Params::BP_Yogurt_Scripting_C_Get_Next_Array_Item Parms{};

	Parms.Array = std::move(Array);
	Parms.PreviousArrayItem = PreviousArrayItem;

	UObject::ProcessEvent(Func, &Parms);

	Array = std::move(Parms.Array);

	if (RandomArrayItem != nullptr)
		*RandomArrayItem = Parms.RandomArrayItem;
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.FadeDynamicVOCallouts
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    WasSoundPlaying                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Yogurt_Scripting_C::FadeDynamicVOCallouts(bool* WasSoundPlaying)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "FadeDynamicVOCallouts");

	Params::BP_Yogurt_Scripting_C_FadeDynamicVOCallouts Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (WasSoundPlaying != nullptr)
		*WasSoundPlaying = Parms.WasSoundPlaying;
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.GetRandomArrayItem
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class USoundCue*>                Array                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class USoundCue*                        PreviousArrayItem                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USoundCue*                        RandomArrayItem                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::GetRandomArrayItem(TArray<class USoundCue*>& Array, class USoundCue* PreviousArrayItem, class USoundCue** RandomArrayItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "GetRandomArrayItem");

	Params::BP_Yogurt_Scripting_C_GetRandomArrayItem Parms{};

	Parms.Array = std::move(Array);
	Parms.PreviousArrayItem = PreviousArrayItem;

	UObject::ProcessEvent(Func, &Parms);

	Array = std::move(Parms.Array);

	if (RandomArrayItem != nullptr)
		*RandomArrayItem = Parms.RandomArrayItem;
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SetupClientBoundaries
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::SetupClientBoundaries()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SetupClientBoundaries");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.SetupServerBoundaries
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::SetupServerBoundaries()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "SetupServerBoundaries");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ApplyBoundaryKnockback
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerControllerAthena*      PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_BoundaryEnforcer_C*           Boundary                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ApplyBoundaryKnockback(class AFortPlayerControllerAthena* PC, class ABP_BoundaryEnforcer_C* Boundary)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ApplyBoundaryKnockback");

	Params::BP_Yogurt_Scripting_C_ApplyBoundaryKnockback Parms{};

	Parms.PC = PC;
	Parms.Boundary = Boundary;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PlayRealityWaveHitFF
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::PlayRealityWaveHitFF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PlayRealityWaveHitFF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.PlayTeleportFF
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Yogurt_Scripting_C::PlayTeleportFF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "PlayTeleportFF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Yogurt_Scripting.BP_Yogurt_Scripting_C.ApplyTeleportMovementSpeedDebuff
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerPawn*                  TeleportedPlayerPawn                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Yogurt_Scripting_C::ApplyTeleportMovementSpeedDebuff(class AFortPlayerPawn* TeleportedPlayerPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Yogurt_Scripting_C", "ApplyTeleportMovementSpeedDebuff");

	Params::BP_Yogurt_Scripting_C_ApplyTeleportMovementSpeedDebuff Parms{};

	Parms.TeleportedPlayerPawn = TeleportedPlayerPawn;

	UObject::ProcessEvent(Func, &Parms);
}

}

