#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DaybreakUI

#include "Basic.hpp"

#include "DaybreakRuntime_structs.hpp"
#include "DaybreakUI_structs.hpp"


namespace SDK::Params
{

// Function DaybreakUI.DaybreakWidgetBase.MutatorReady
// 0x0008 (0x0008 - 0x0000)
struct DaybreakWidgetBase_MutatorReady final
{
public:
	const class AFortAthenaMutator_Daybreak*      MutatorActor;                                      // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakWidgetBase_MutatorReady) == 0x000008, "Wrong alignment on DaybreakWidgetBase_MutatorReady");
static_assert(sizeof(DaybreakWidgetBase_MutatorReady) == 0x000008, "Wrong size on DaybreakWidgetBase_MutatorReady");
static_assert(offsetof(DaybreakWidgetBase_MutatorReady, MutatorActor) == 0x000000, "Member 'DaybreakWidgetBase_MutatorReady::MutatorActor' has a wrong offset!");

// Function DaybreakUI.DaybreakWidgetBase.GetDaybreakMutator
// 0x0008 (0x0008 - 0x0000)
struct DaybreakWidgetBase_GetDaybreakMutator final
{
public:
	class AFortAthenaMutator_Daybreak*            ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakWidgetBase_GetDaybreakMutator) == 0x000008, "Wrong alignment on DaybreakWidgetBase_GetDaybreakMutator");
static_assert(sizeof(DaybreakWidgetBase_GetDaybreakMutator) == 0x000008, "Wrong size on DaybreakWidgetBase_GetDaybreakMutator");
static_assert(offsetof(DaybreakWidgetBase_GetDaybreakMutator, ReturnValue) == 0x000000, "Member 'DaybreakWidgetBase_GetDaybreakMutator::ReturnValue' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusEntryWidget.NativeOnDaybreakSquadMemberDroppedPart
// 0x0018 (0x0018 - 0x0000)
struct DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart final
{
public:
	const class UFortItemDefinition*              VehiclePartItemDefinition;                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AActor>                     VehiclePartClass;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class APlayerState*                     PlayerWhoDroppedPart;                              // 0x0010(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart) == 0x000008, "Wrong alignment on DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart");
static_assert(sizeof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart) == 0x000018, "Wrong size on DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart, VehiclePartItemDefinition) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart::VehiclePartItemDefinition' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart, VehiclePartClass) == 0x000008, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart::VehiclePartClass' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart, PlayerWhoDroppedPart) == 0x000010, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberDroppedPart::PlayerWhoDroppedPart' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusEntryWidget.NativeOnDaybreakSquadMemberPickedUpPart
// 0x0018 (0x0018 - 0x0000)
struct DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart final
{
public:
	const class UFortItemDefinition*              VehiclePartItemDefinition;                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AActor>                     VehiclePartClass;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class APlayerState*                     PlayerWhoPickedUpPart;                             // 0x0010(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart) == 0x000008, "Wrong alignment on DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart");
static_assert(sizeof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart) == 0x000018, "Wrong size on DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart, VehiclePartItemDefinition) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart::VehiclePartItemDefinition' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart, VehiclePartClass) == 0x000008, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart::VehiclePartClass' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart, PlayerWhoPickedUpPart) == 0x000010, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnDaybreakSquadMemberPickedUpPart::PlayerWhoPickedUpPart' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusEntryWidget.NativeOnLevelExitVehicleDestroyed
// 0x0001 (0x0001 - 0x0000)
struct DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleDestroyed final
{
public:
	uint8                                         InLevelExitVehicleId;                              // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleDestroyed) == 0x000001, "Wrong alignment on DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleDestroyed");
static_assert(sizeof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleDestroyed) == 0x000001, "Wrong size on DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleDestroyed");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleDestroyed, InLevelExitVehicleId) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleDestroyed::InLevelExitVehicleId' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusEntryWidget.NativeOnLevelExitVehicleEscaped
// 0x0001 (0x0001 - 0x0000)
struct DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleEscaped final
{
public:
	uint8                                         InLevelExitVehicleId;                              // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleEscaped) == 0x000001, "Wrong alignment on DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleEscaped");
static_assert(sizeof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleEscaped) == 0x000001, "Wrong size on DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleEscaped");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleEscaped, InLevelExitVehicleId) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehicleEscaped::InLevelExitVehicleId' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusEntryWidget.NativeOnLevelExitVehiclePartAdded
// 0x0028 (0x0028 - 0x0000)
struct DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded final
{
public:
	uint8                                         InLevelExitVehicleId;                              // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class UFortWorldItemDefinition*         PartAdded_WorldItemDefinition;                     // 0x0008(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AActor>                     PartAdded_ActorClass;                              // 0x0010(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumberOfPartsRemaining;                            // 0x0018(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class AFortPlayerState*                 PlayerStateThatAddedPart;                          // 0x0020(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded) == 0x000008, "Wrong alignment on DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded");
static_assert(sizeof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded) == 0x000028, "Wrong size on DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded, InLevelExitVehicleId) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded::InLevelExitVehicleId' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded, PartAdded_WorldItemDefinition) == 0x000008, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded::PartAdded_WorldItemDefinition' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded, PartAdded_ActorClass) == 0x000010, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded::PartAdded_ActorClass' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded, NumberOfPartsRemaining) == 0x000018, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded::NumberOfPartsRemaining' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded, PlayerStateThatAddedPart) == 0x000020, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_NativeOnLevelExitVehiclePartAdded::PlayerStateThatAddedPart' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusEntryWidget.OnDaybreakSquadMemberDroppedPart
// 0x0010 (0x0010 - 0x0000)
struct DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberDroppedPart final
{
public:
	const class UFortItemDefinition*              PartDropped_ItemDefinition;                        // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AActor>                     PartDropped_ActorClass;                            // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberDroppedPart) == 0x000008, "Wrong alignment on DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberDroppedPart");
static_assert(sizeof(DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberDroppedPart) == 0x000010, "Wrong size on DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberDroppedPart");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberDroppedPart, PartDropped_ItemDefinition) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberDroppedPart::PartDropped_ItemDefinition' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberDroppedPart, PartDropped_ActorClass) == 0x000008, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberDroppedPart::PartDropped_ActorClass' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusEntryWidget.OnDaybreakSquadMemberPickedUpPart
// 0x0010 (0x0010 - 0x0000)
struct DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberPickedUpPart final
{
public:
	const class UFortItemDefinition*              PartPickedUp_ItemDefinition;                       // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AActor>                     PartPickedUp_ActorClass;                           // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberPickedUpPart) == 0x000008, "Wrong alignment on DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberPickedUpPart");
static_assert(sizeof(DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberPickedUpPart) == 0x000010, "Wrong size on DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberPickedUpPart");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberPickedUpPart, PartPickedUp_ItemDefinition) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberPickedUpPart::PartPickedUp_ItemDefinition' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberPickedUpPart, PartPickedUp_ActorClass) == 0x000008, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_OnDaybreakSquadMemberPickedUpPart::PartPickedUp_ActorClass' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusEntryWidget.OnLevelExitVehiclePartAdded
// 0x0018 (0x0018 - 0x0000)
struct DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded final
{
public:
	const class UFortWorldItemDefinition*         PartAdded_WorldItemDefinition;                     // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AActor>                     PartAdded_ActorClass;                              // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumberOfPartsRemaining;                            // 0x0010(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded) == 0x000008, "Wrong alignment on DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded");
static_assert(sizeof(DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded) == 0x000018, "Wrong size on DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded, PartAdded_WorldItemDefinition) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded::PartAdded_WorldItemDefinition' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded, PartAdded_ActorClass) == 0x000008, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded::PartAdded_ActorClass' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded, NumberOfPartsRemaining) == 0x000010, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_OnLevelExitVehiclePartAdded::NumberOfPartsRemaining' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusEntryWidget.SetLevelExitVehicle
// 0x0040 (0x0040 - 0x0000)
struct DaybreakLevelExitVehicleStatusEntryWidget_SetLevelExitVehicle final
{
public:
	struct FDaybreakLevelExitVehicleData          InLevelExitVehicleData;                            // 0x0000(0x0040)(Parm, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusEntryWidget_SetLevelExitVehicle) == 0x000008, "Wrong alignment on DaybreakLevelExitVehicleStatusEntryWidget_SetLevelExitVehicle");
static_assert(sizeof(DaybreakLevelExitVehicleStatusEntryWidget_SetLevelExitVehicle) == 0x000040, "Wrong size on DaybreakLevelExitVehicleStatusEntryWidget_SetLevelExitVehicle");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_SetLevelExitVehicle, InLevelExitVehicleData) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_SetLevelExitVehicle::InLevelExitVehicleData' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusEntryWidget.CanUpdateDaybreakLevelExitVehicleStatus
// 0x0002 (0x0002 - 0x0000)
struct DaybreakLevelExitVehicleStatusEntryWidget_CanUpdateDaybreakLevelExitVehicleStatus final
{
public:
	EDaybreakLevelExitVehicleStatus               StatusToUpdateTo;                                  // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusEntryWidget_CanUpdateDaybreakLevelExitVehicleStatus) == 0x000001, "Wrong alignment on DaybreakLevelExitVehicleStatusEntryWidget_CanUpdateDaybreakLevelExitVehicleStatus");
static_assert(sizeof(DaybreakLevelExitVehicleStatusEntryWidget_CanUpdateDaybreakLevelExitVehicleStatus) == 0x000002, "Wrong size on DaybreakLevelExitVehicleStatusEntryWidget_CanUpdateDaybreakLevelExitVehicleStatus");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_CanUpdateDaybreakLevelExitVehicleStatus, StatusToUpdateTo) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_CanUpdateDaybreakLevelExitVehicleStatus::StatusToUpdateTo' has a wrong offset!");
static_assert(offsetof(DaybreakLevelExitVehicleStatusEntryWidget_CanUpdateDaybreakLevelExitVehicleStatus, ReturnValue) == 0x000001, "Member 'DaybreakLevelExitVehicleStatusEntryWidget_CanUpdateDaybreakLevelExitVehicleStatus::ReturnValue' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusWidget.BP_SetLevelExitVehicleReferences
// 0x0040 (0x0040 - 0x0000)
struct DaybreakLevelExitVehicleStatusWidget_BP_SetLevelExitVehicleReferences final
{
public:
	struct FDaybreakLevelExitVehicleData          LevelExitVehicleData;                              // 0x0000(0x0040)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusWidget_BP_SetLevelExitVehicleReferences) == 0x000008, "Wrong alignment on DaybreakLevelExitVehicleStatusWidget_BP_SetLevelExitVehicleReferences");
static_assert(sizeof(DaybreakLevelExitVehicleStatusWidget_BP_SetLevelExitVehicleReferences) == 0x000040, "Wrong size on DaybreakLevelExitVehicleStatusWidget_BP_SetLevelExitVehicleReferences");
static_assert(offsetof(DaybreakLevelExitVehicleStatusWidget_BP_SetLevelExitVehicleReferences, LevelExitVehicleData) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusWidget_BP_SetLevelExitVehicleReferences::LevelExitVehicleData' has a wrong offset!");

// Function DaybreakUI.DaybreakLevelExitVehicleStatusWidget.HandleOnDaybreakLevelExitVehicleDataUpdated
// 0x0001 (0x0001 - 0x0000)
struct DaybreakLevelExitVehicleStatusWidget_HandleOnDaybreakLevelExitVehicleDataUpdated final
{
public:
	uint8                                         UpdatedLevelExitVehicleID;                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakLevelExitVehicleStatusWidget_HandleOnDaybreakLevelExitVehicleDataUpdated) == 0x000001, "Wrong alignment on DaybreakLevelExitVehicleStatusWidget_HandleOnDaybreakLevelExitVehicleDataUpdated");
static_assert(sizeof(DaybreakLevelExitVehicleStatusWidget_HandleOnDaybreakLevelExitVehicleDataUpdated) == 0x000001, "Wrong size on DaybreakLevelExitVehicleStatusWidget_HandleOnDaybreakLevelExitVehicleDataUpdated");
static_assert(offsetof(DaybreakLevelExitVehicleStatusWidget_HandleOnDaybreakLevelExitVehicleDataUpdated, UpdatedLevelExitVehicleID) == 0x000000, "Member 'DaybreakLevelExitVehicleStatusWidget_HandleOnDaybreakLevelExitVehicleDataUpdated::UpdatedLevelExitVehicleID' has a wrong offset!");

// Function DaybreakUI.DaybreakMapSquadInfoWidget.HandleGameMemberChanged
// 0x0010 (0x0010 - 0x0000)
struct DaybreakMapSquadInfoWidget_HandleGameMemberChanged final
{
public:
	uint8                                         InSquadId;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         InTeamIndex;                                       // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerStateAthena*                 ChangedPS;                                         // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakMapSquadInfoWidget_HandleGameMemberChanged) == 0x000008, "Wrong alignment on DaybreakMapSquadInfoWidget_HandleGameMemberChanged");
static_assert(sizeof(DaybreakMapSquadInfoWidget_HandleGameMemberChanged) == 0x000010, "Wrong size on DaybreakMapSquadInfoWidget_HandleGameMemberChanged");
static_assert(offsetof(DaybreakMapSquadInfoWidget_HandleGameMemberChanged, InSquadId) == 0x000000, "Member 'DaybreakMapSquadInfoWidget_HandleGameMemberChanged::InSquadId' has a wrong offset!");
static_assert(offsetof(DaybreakMapSquadInfoWidget_HandleGameMemberChanged, InTeamIndex) == 0x000001, "Member 'DaybreakMapSquadInfoWidget_HandleGameMemberChanged::InTeamIndex' has a wrong offset!");
static_assert(offsetof(DaybreakMapSquadInfoWidget_HandleGameMemberChanged, ChangedPS) == 0x000008, "Member 'DaybreakMapSquadInfoWidget_HandleGameMemberChanged::ChangedPS' has a wrong offset!");

// Function DaybreakUI.DaybreakMapSquadInfoWidget.HandleSquadMemberDisconnected
// 0x0008 (0x0008 - 0x0000)
struct DaybreakMapSquadInfoWidget_HandleSquadMemberDisconnected final
{
public:
	const class AFortPlayerStateAthena*           DisconnectedSquadMember;                           // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakMapSquadInfoWidget_HandleSquadMemberDisconnected) == 0x000008, "Wrong alignment on DaybreakMapSquadInfoWidget_HandleSquadMemberDisconnected");
static_assert(sizeof(DaybreakMapSquadInfoWidget_HandleSquadMemberDisconnected) == 0x000008, "Wrong size on DaybreakMapSquadInfoWidget_HandleSquadMemberDisconnected");
static_assert(offsetof(DaybreakMapSquadInfoWidget_HandleSquadMemberDisconnected, DisconnectedSquadMember) == 0x000000, "Member 'DaybreakMapSquadInfoWidget_HandleSquadMemberDisconnected::DisconnectedSquadMember' has a wrong offset!");

// Function DaybreakUI.DaybreakMapSquadInfoWidget.HandleViewModelUpdate
// 0x0008 (0x0008 - 0x0000)
struct DaybreakMapSquadInfoWidget_HandleViewModelUpdate final
{
public:
	class UAthenaPlayerViewModel*                 InPlayerViewModel;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakMapSquadInfoWidget_HandleViewModelUpdate) == 0x000008, "Wrong alignment on DaybreakMapSquadInfoWidget_HandleViewModelUpdate");
static_assert(sizeof(DaybreakMapSquadInfoWidget_HandleViewModelUpdate) == 0x000008, "Wrong size on DaybreakMapSquadInfoWidget_HandleViewModelUpdate");
static_assert(offsetof(DaybreakMapSquadInfoWidget_HandleViewModelUpdate, InPlayerViewModel) == 0x000000, "Member 'DaybreakMapSquadInfoWidget_HandleViewModelUpdate::InPlayerViewModel' has a wrong offset!");

// Function DaybreakUI.DaybreakMapSquadInfoWidget.SetPlayerImageByPlayerState
// 0x0010 (0x0010 - 0x0000)
struct DaybreakMapSquadInfoWidget_SetPlayerImageByPlayerState final
{
public:
	const class AFortPlayerStateAthena*           InFortPlayerStateAthena;                           // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFortLazyImage*                         PlayerImage;                                       // 0x0008(0x0008)(Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakMapSquadInfoWidget_SetPlayerImageByPlayerState) == 0x000008, "Wrong alignment on DaybreakMapSquadInfoWidget_SetPlayerImageByPlayerState");
static_assert(sizeof(DaybreakMapSquadInfoWidget_SetPlayerImageByPlayerState) == 0x000010, "Wrong size on DaybreakMapSquadInfoWidget_SetPlayerImageByPlayerState");
static_assert(offsetof(DaybreakMapSquadInfoWidget_SetPlayerImageByPlayerState, InFortPlayerStateAthena) == 0x000000, "Member 'DaybreakMapSquadInfoWidget_SetPlayerImageByPlayerState::InFortPlayerStateAthena' has a wrong offset!");
static_assert(offsetof(DaybreakMapSquadInfoWidget_SetPlayerImageByPlayerState, PlayerImage) == 0x000008, "Member 'DaybreakMapSquadInfoWidget_SetPlayerImageByPlayerState::PlayerImage' has a wrong offset!");

// Function DaybreakUI.DaybreakMapSquadInfoWidget.GetSquadMembersFromViewModel
// 0x0010 (0x0010 - 0x0000)
struct DaybreakMapSquadInfoWidget_GetSquadMembersFromViewModel final
{
public:
	TArray<class AFortPlayerStateAthena*>         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakMapSquadInfoWidget_GetSquadMembersFromViewModel) == 0x000008, "Wrong alignment on DaybreakMapSquadInfoWidget_GetSquadMembersFromViewModel");
static_assert(sizeof(DaybreakMapSquadInfoWidget_GetSquadMembersFromViewModel) == 0x000010, "Wrong size on DaybreakMapSquadInfoWidget_GetSquadMembersFromViewModel");
static_assert(offsetof(DaybreakMapSquadInfoWidget_GetSquadMembersFromViewModel, ReturnValue) == 0x000000, "Member 'DaybreakMapSquadInfoWidget_GetSquadMembersFromViewModel::ReturnValue' has a wrong offset!");

// Function DaybreakUI.DaybreakSquadMemberStatusWidget.NativeOnDaybreakPlayerEnteredLevelExitVehicle
// 0x0010 (0x0010 - 0x0000)
struct DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerEnteredLevelExitVehicle final
{
public:
	const class APlayerState*                     PlayerState;                                       // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         LevelExitVehicleId;                                // 0x0008(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerEnteredLevelExitVehicle) == 0x000008, "Wrong alignment on DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerEnteredLevelExitVehicle");
static_assert(sizeof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerEnteredLevelExitVehicle) == 0x000010, "Wrong size on DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerEnteredLevelExitVehicle");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerEnteredLevelExitVehicle, PlayerState) == 0x000000, "Member 'DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerEnteredLevelExitVehicle::PlayerState' has a wrong offset!");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerEnteredLevelExitVehicle, LevelExitVehicleId) == 0x000008, "Member 'DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerEnteredLevelExitVehicle::LevelExitVehicleId' has a wrong offset!");

// Function DaybreakUI.DaybreakSquadMemberStatusWidget.NativeOnDaybreakPlayerExitedLevelExitVehicle
// 0x0010 (0x0010 - 0x0000)
struct DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerExitedLevelExitVehicle final
{
public:
	const class APlayerState*                     PlayerState;                                       // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         LevelExitVehicleId;                                // 0x0008(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerExitedLevelExitVehicle) == 0x000008, "Wrong alignment on DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerExitedLevelExitVehicle");
static_assert(sizeof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerExitedLevelExitVehicle) == 0x000010, "Wrong size on DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerExitedLevelExitVehicle");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerExitedLevelExitVehicle, PlayerState) == 0x000000, "Member 'DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerExitedLevelExitVehicle::PlayerState' has a wrong offset!");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerExitedLevelExitVehicle, LevelExitVehicleId) == 0x000008, "Member 'DaybreakSquadMemberStatusWidget_NativeOnDaybreakPlayerExitedLevelExitVehicle::LevelExitVehicleId' has a wrong offset!");

// Function DaybreakUI.DaybreakSquadMemberStatusWidget.NativeOnDaybreakSquadMemberDroppedPart
// 0x0018 (0x0018 - 0x0000)
struct DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart final
{
public:
	const class UFortItemDefinition*              VehiclePartItemDefinition;                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AActor>                     VehiclePartClass;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class APlayerState*                     PlayerWhoDroppedPart;                              // 0x0010(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart) == 0x000008, "Wrong alignment on DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart");
static_assert(sizeof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart) == 0x000018, "Wrong size on DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart, VehiclePartItemDefinition) == 0x000000, "Member 'DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart::VehiclePartItemDefinition' has a wrong offset!");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart, VehiclePartClass) == 0x000008, "Member 'DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart::VehiclePartClass' has a wrong offset!");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart, PlayerWhoDroppedPart) == 0x000010, "Member 'DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberDroppedPart::PlayerWhoDroppedPart' has a wrong offset!");

// Function DaybreakUI.DaybreakSquadMemberStatusWidget.NativeOnDaybreakSquadMemberPickedUpPart
// 0x0018 (0x0018 - 0x0000)
struct DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart final
{
public:
	const class UFortItemDefinition*              VehiclePartItemDefinition;                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AActor>                     VehiclePartClass;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	const class APlayerState*                     PlayerWhoPickedUpPart;                             // 0x0010(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart) == 0x000008, "Wrong alignment on DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart");
static_assert(sizeof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart) == 0x000018, "Wrong size on DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart, VehiclePartItemDefinition) == 0x000000, "Member 'DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart::VehiclePartItemDefinition' has a wrong offset!");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart, VehiclePartClass) == 0x000008, "Member 'DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart::VehiclePartClass' has a wrong offset!");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart, PlayerWhoPickedUpPart) == 0x000010, "Member 'DaybreakSquadMemberStatusWidget_NativeOnDaybreakSquadMemberPickedUpPart::PlayerWhoPickedUpPart' has a wrong offset!");

// Function DaybreakUI.DaybreakSquadMemberStatusWidget.SetLevelExitVehicleIconByVehicleID
// 0x0001 (0x0001 - 0x0000)
struct DaybreakSquadMemberStatusWidget_SetLevelExitVehicleIconByVehicleID final
{
public:
	uint8                                         LevelExitVehicleId;                                // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakSquadMemberStatusWidget_SetLevelExitVehicleIconByVehicleID) == 0x000001, "Wrong alignment on DaybreakSquadMemberStatusWidget_SetLevelExitVehicleIconByVehicleID");
static_assert(sizeof(DaybreakSquadMemberStatusWidget_SetLevelExitVehicleIconByVehicleID) == 0x000001, "Wrong size on DaybreakSquadMemberStatusWidget_SetLevelExitVehicleIconByVehicleID");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_SetLevelExitVehicleIconByVehicleID, LevelExitVehicleId) == 0x000000, "Member 'DaybreakSquadMemberStatusWidget_SetLevelExitVehicleIconByVehicleID::LevelExitVehicleId' has a wrong offset!");

// Function DaybreakUI.DaybreakSquadMemberStatusWidget.SetRepresentedVehiclePart
// 0x0008 (0x0008 - 0x0000)
struct DaybreakSquadMemberStatusWidget_SetRepresentedVehiclePart final
{
public:
	const class UFortWorldItemDefinition*         VehiclePartItemDefinition;                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DaybreakSquadMemberStatusWidget_SetRepresentedVehiclePart) == 0x000008, "Wrong alignment on DaybreakSquadMemberStatusWidget_SetRepresentedVehiclePart");
static_assert(sizeof(DaybreakSquadMemberStatusWidget_SetRepresentedVehiclePart) == 0x000008, "Wrong size on DaybreakSquadMemberStatusWidget_SetRepresentedVehiclePart");
static_assert(offsetof(DaybreakSquadMemberStatusWidget_SetRepresentedVehiclePart, VehiclePartItemDefinition) == 0x000000, "Member 'DaybreakSquadMemberStatusWidget_SetRepresentedVehiclePart::VehiclePartItemDefinition' has a wrong offset!");

}

