#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EArrowAdditionalSpawnType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EArrowAdditionalSpawnType.EArrowAdditionalSpawnType
// NumValues: 0x0004
enum class EArrowAdditionalSpawnType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	EArrowAdditionalSpawnType_MAX            = 3,
};

}

