#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_Knockback_Parent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Athena_Knockback_Parent_Type_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_Knockback_Parent.GA_Athena_Knockback_Parent_C
// 0x0298 (0x0D08 - 0x0A70)
class UGA_Athena_Knockback_Parent_C : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A70(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AActor*                                 Launcher;                                          // 0x0A78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Target;                                            // 0x0A80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  TC_TagsToIgnore;                                   // 0x0A88(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Row_XYKnockMag;                                    // 0x0AA8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Row_ZKnockMag;                                     // 0x0AD0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Row_ZAdd;                                          // 0x0AF8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          ZAlwayzPositive;                                   // 0x0B20(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          KnockTowardsLauncher;                              // 0x0B21(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B22[0x6];                                      // 0x0B22(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         Row_ZVelPercentMaintained;                         // 0x0B28(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Row_XYVelPercentMaintained;                        // 0x0B50(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Row_PhysicsObjectImpulseMultiplier;                // 0x0B78(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTagContainer                  DefaultTags;                                       // 0x0BA0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, AdvancedDisplay)
	struct FVector                                FinalLaunchVel;                                    // 0x0BC0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	float                                         DistanceMagMult;                                   // 0x0BCC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	float                                         Distance;                                          // 0x0BD0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	float                                         LaunchDuration;                                    // 0x0BD4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          XYMagUsesInstigatorDistanceMod;                    // 0x0BD8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ZMagUsesInstigatorDistanceMod;                     // 0x0BD9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BDA[0x6];                                      // 0x0BDA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         Row_MinDistance;                                   // 0x0BE0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Row_MaxDistance;                                   // 0x0C08(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          ResetFallHeight;                                   // 0x0C30(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ImpulseMustBePositiveForReset;                     // 0x0C31(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	EAthena_Knockback_Parent_Type                 LaunchType;                                        // 0x0C32(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          KnocksVehicles;                                    // 0x0C33(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C34[0x4];                                      // 0x0C34(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         Row_VehicleXYMult;                                 // 0x0C38(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Row_VehicleZMult;                                  // 0x0C60(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	ERootMotionFinishVelocityMode                 VelocityOnFinish;                                  // 0x0C88(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C89[0x3];                                      // 0x0C89(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                SetVelocityOnFinish;                               // 0x0C8C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ClampVelocityOnFinish;                             // 0x0C98(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UsesGravity;                                       // 0x0C9C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, Interp, NoDestructor)
	bool                                          AccountsForGravityZScale;                          // 0x0C9D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9E[0x2];                                      // 0x0C9E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LowZGravityDampenerIntensity;                      // 0x0CA0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HighZGravityMultiplierIntensity;                   // 0x0CA4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCurveFloat*                            Curve_StrengthOverTime;                            // 0x0CA8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCurveVector*                           Curve_PathOffset;                                  // 0x0CB0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_Knockback_Status;                               // 0x0CB8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShouldApplyKnockbackStatus;                        // 0x0CC0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          SetKnockbackDurationEqualToLaunchDuration;         // 0x0CC1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CC2[0x6];                                      // 0x0CC2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         Row_KnockbackDuration;                             // 0x0CC8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         LocalGravityScale;                                 // 0x0CF0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Tag_BuildingPhysics;                               // 0x0CF4(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	float                                         FailsafeDelay;                                     // 0x0CFC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           KnockbackTypeTag;                                  // 0x0D00(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Athena_Knockback_Parent(int32 EntryPoint);
	void FailsafeEndAbility();
	void OwningPawnDied(class AActor* DamagedActor, float Damage, class AController* InstigatedBy, class AActor* DamageCauser, const struct FVector& HitLocation, class UPrimitiveComponent* FHitComponent, class FName BoneName, const struct FVector& Momentum);
	void LaunchBuldingActors(class AActor* Actor);
	void LaunchFinished();
	void DoLaunch(const struct FVector& Vel);
	void K2_ActivateAbility();
	void OnTimedOut_C8C9B5D948887DE06B469CAFC5621C02();
	void OnTimedOutAndDestinationReached_C8C9B5D948887DE06B469CAFC5621C02();
	void OnFinish_78B7A0C144DB79535B9890B75AE5F853();
	void CalculateVelocityMaintained(class AActor* LaunchTarget, const struct FVector& LaunchMagIn, struct FVector* ModifiedLaunchSpeed);
	void Get_Initial_Knock_Mag(const struct FVector& Direction, struct FVector* LaunchMag);
	struct FVector GetKnockbackOrigin(class AActor* OriginActor);
	void CalculateDistanceMod(const struct FVector& TargetLocation, const struct FVector& KnockOrigin, float* ModAmount, bool* AboveMax);
	struct FVector CalcVehicleMult(const struct FVector& InVec);
	struct FVector GetTargetLocation();
	void Find_Launcher(class AActor* DefaultLauncher, class AActor** LauncherOut);
	float CheckGravityScale(const struct FGameplayAttribute& Attribute_Gravity_Scale);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_Knockback_Parent_C">();
	}
	static class UGA_Athena_Knockback_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_Knockback_Parent_C>();
	}
};
static_assert(alignof(UGA_Athena_Knockback_Parent_C) == 0x000008, "Wrong alignment on UGA_Athena_Knockback_Parent_C");
static_assert(sizeof(UGA_Athena_Knockback_Parent_C) == 0x000D08, "Wrong size on UGA_Athena_Knockback_Parent_C");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, UberGraphFrame) == 0x000A70, "Member 'UGA_Athena_Knockback_Parent_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Launcher) == 0x000A78, "Member 'UGA_Athena_Knockback_Parent_C::Launcher' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Target) == 0x000A80, "Member 'UGA_Athena_Knockback_Parent_C::Target' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, TC_TagsToIgnore) == 0x000A88, "Member 'UGA_Athena_Knockback_Parent_C::TC_TagsToIgnore' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_XYKnockMag) == 0x000AA8, "Member 'UGA_Athena_Knockback_Parent_C::Row_XYKnockMag' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_ZKnockMag) == 0x000AD0, "Member 'UGA_Athena_Knockback_Parent_C::Row_ZKnockMag' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_ZAdd) == 0x000AF8, "Member 'UGA_Athena_Knockback_Parent_C::Row_ZAdd' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, ZAlwayzPositive) == 0x000B20, "Member 'UGA_Athena_Knockback_Parent_C::ZAlwayzPositive' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, KnockTowardsLauncher) == 0x000B21, "Member 'UGA_Athena_Knockback_Parent_C::KnockTowardsLauncher' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_ZVelPercentMaintained) == 0x000B28, "Member 'UGA_Athena_Knockback_Parent_C::Row_ZVelPercentMaintained' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_XYVelPercentMaintained) == 0x000B50, "Member 'UGA_Athena_Knockback_Parent_C::Row_XYVelPercentMaintained' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_PhysicsObjectImpulseMultiplier) == 0x000B78, "Member 'UGA_Athena_Knockback_Parent_C::Row_PhysicsObjectImpulseMultiplier' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, DefaultTags) == 0x000BA0, "Member 'UGA_Athena_Knockback_Parent_C::DefaultTags' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, FinalLaunchVel) == 0x000BC0, "Member 'UGA_Athena_Knockback_Parent_C::FinalLaunchVel' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, DistanceMagMult) == 0x000BCC, "Member 'UGA_Athena_Knockback_Parent_C::DistanceMagMult' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Distance) == 0x000BD0, "Member 'UGA_Athena_Knockback_Parent_C::Distance' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, LaunchDuration) == 0x000BD4, "Member 'UGA_Athena_Knockback_Parent_C::LaunchDuration' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, XYMagUsesInstigatorDistanceMod) == 0x000BD8, "Member 'UGA_Athena_Knockback_Parent_C::XYMagUsesInstigatorDistanceMod' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, ZMagUsesInstigatorDistanceMod) == 0x000BD9, "Member 'UGA_Athena_Knockback_Parent_C::ZMagUsesInstigatorDistanceMod' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_MinDistance) == 0x000BE0, "Member 'UGA_Athena_Knockback_Parent_C::Row_MinDistance' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_MaxDistance) == 0x000C08, "Member 'UGA_Athena_Knockback_Parent_C::Row_MaxDistance' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, ResetFallHeight) == 0x000C30, "Member 'UGA_Athena_Knockback_Parent_C::ResetFallHeight' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, ImpulseMustBePositiveForReset) == 0x000C31, "Member 'UGA_Athena_Knockback_Parent_C::ImpulseMustBePositiveForReset' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, LaunchType) == 0x000C32, "Member 'UGA_Athena_Knockback_Parent_C::LaunchType' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, KnocksVehicles) == 0x000C33, "Member 'UGA_Athena_Knockback_Parent_C::KnocksVehicles' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_VehicleXYMult) == 0x000C38, "Member 'UGA_Athena_Knockback_Parent_C::Row_VehicleXYMult' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_VehicleZMult) == 0x000C60, "Member 'UGA_Athena_Knockback_Parent_C::Row_VehicleZMult' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, VelocityOnFinish) == 0x000C88, "Member 'UGA_Athena_Knockback_Parent_C::VelocityOnFinish' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, SetVelocityOnFinish) == 0x000C8C, "Member 'UGA_Athena_Knockback_Parent_C::SetVelocityOnFinish' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, ClampVelocityOnFinish) == 0x000C98, "Member 'UGA_Athena_Knockback_Parent_C::ClampVelocityOnFinish' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, UsesGravity) == 0x000C9C, "Member 'UGA_Athena_Knockback_Parent_C::UsesGravity' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, AccountsForGravityZScale) == 0x000C9D, "Member 'UGA_Athena_Knockback_Parent_C::AccountsForGravityZScale' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, LowZGravityDampenerIntensity) == 0x000CA0, "Member 'UGA_Athena_Knockback_Parent_C::LowZGravityDampenerIntensity' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, HighZGravityMultiplierIntensity) == 0x000CA4, "Member 'UGA_Athena_Knockback_Parent_C::HighZGravityMultiplierIntensity' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Curve_StrengthOverTime) == 0x000CA8, "Member 'UGA_Athena_Knockback_Parent_C::Curve_StrengthOverTime' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Curve_PathOffset) == 0x000CB0, "Member 'UGA_Athena_Knockback_Parent_C::Curve_PathOffset' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, GE_Knockback_Status) == 0x000CB8, "Member 'UGA_Athena_Knockback_Parent_C::GE_Knockback_Status' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, ShouldApplyKnockbackStatus) == 0x000CC0, "Member 'UGA_Athena_Knockback_Parent_C::ShouldApplyKnockbackStatus' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, SetKnockbackDurationEqualToLaunchDuration) == 0x000CC1, "Member 'UGA_Athena_Knockback_Parent_C::SetKnockbackDurationEqualToLaunchDuration' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Row_KnockbackDuration) == 0x000CC8, "Member 'UGA_Athena_Knockback_Parent_C::Row_KnockbackDuration' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, LocalGravityScale) == 0x000CF0, "Member 'UGA_Athena_Knockback_Parent_C::LocalGravityScale' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, Tag_BuildingPhysics) == 0x000CF4, "Member 'UGA_Athena_Knockback_Parent_C::Tag_BuildingPhysics' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, FailsafeDelay) == 0x000CFC, "Member 'UGA_Athena_Knockback_Parent_C::FailsafeDelay' has a wrong offset!");
static_assert(offsetof(UGA_Athena_Knockback_Parent_C, KnockbackTypeTag) == 0x000D00, "Member 'UGA_Athena_Knockback_Parent_C::KnockbackTypeTag' has a wrong offset!");

}

