#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Bow_Splinter_Athena

#include "Basic.hpp"

#include "GA_Athena_Bow_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Bow_Splinter_Athena.GA_Bow_Splinter_Athena_C
// 0x0000 (0x0AB8 - 0x0AB8)
class UGA_Bow_Splinter_Athena_C final : public UGA_Athena_Bow_Generic_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Bow_Splinter_Athena_C">();
	}
	static class UGA_Bow_Splinter_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Bow_Splinter_Athena_C>();
	}
};
static_assert(alignof(UGA_Bow_Splinter_Athena_C) == 0x000008, "Wrong alignment on UGA_Bow_Splinter_Athena_C");
static_assert(sizeof(UGA_Bow_Splinter_Athena_C) == 0x000AB8, "Wrong size on UGA_Bow_Splinter_Athena_C");

}

