#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Daybreak_ThrowPart

#include "Basic.hpp"

#include "GA_Daybreak_ThrowPart_classes.hpp"
#include "GA_Daybreak_ThrowPart_parameters.hpp"


namespace SDK
{

// Function GA_Daybreak_ThrowPart.GA_Daybreak_ThrowPart_C.ExecuteUbergraph_GA_Daybreak_ThrowPart
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Daybreak_ThrowPart_C::ExecuteUbergraph_GA_Daybreak_ThrowPart(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Daybreak_ThrowPart_C", "ExecuteUbergraph_GA_Daybreak_ThrowPart");

	Params::GA_Daybreak_ThrowPart_C_ExecuteUbergraph_GA_Daybreak_ThrowPart Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Daybreak_ThrowPart.GA_Daybreak_ThrowPart_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Daybreak_ThrowPart_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Daybreak_ThrowPart_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Daybreak_ThrowPart.GA_Daybreak_ThrowPart_C.OnAbilityInputReleased
// (Event, Protected, BlueprintEvent)

void UGA_Daybreak_ThrowPart_C::OnAbilityInputReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Daybreak_ThrowPart_C", "OnAbilityInputReleased");

	UObject::ProcessEvent(Func, nullptr);
}

}

