#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_JunkGun_Suction_Knockback

#include "Basic.hpp"

#include "GA_Athena_Knockback_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_JunkGun_Suction_Knockback.GA_JunkGun_Suction_Knockback_C
// 0x0000 (0x0D08 - 0x0D08)
class UGA_JunkGun_Suction_Knockback_C final : public UGA_Athena_Knockback_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_JunkGun_Suction_Knockback_C">();
	}
	static class UGA_JunkGun_Suction_Knockback_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_JunkGun_Suction_Knockback_C>();
	}
};
static_assert(alignof(UGA_JunkGun_Suction_Knockback_C) == 0x000008, "Wrong alignment on UGA_JunkGun_Suction_Knockback_C");
static_assert(sizeof(UGA_JunkGun_Suction_Knockback_C) == 0x000D08, "Wrong size on UGA_JunkGun_Suction_Knockback_C");

}

