#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_NPC_Parent_GrabPickup_Active

#include "Basic.hpp"


namespace SDK::Params
{

// Function GA_NPC_Parent_GrabPickup_Active.GA_NPC_Parent_GrabPickup_Active_C.ExecuteUbergraph_GA_NPC_Parent_GrabPickup_Active
// 0x0004 (0x0004 - 0x0000)
struct GA_NPC_Parent_GrabPickup_Active_C_ExecuteUbergraph_GA_NPC_Parent_GrabPickup_Active final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GA_NPC_Parent_GrabPickup_Active_C_ExecuteUbergraph_GA_NPC_Parent_GrabPickup_Active) == 0x000004, "Wrong alignment on GA_NPC_Parent_GrabPickup_Active_C_ExecuteUbergraph_GA_NPC_Parent_GrabPickup_Active");
static_assert(sizeof(GA_NPC_Parent_GrabPickup_Active_C_ExecuteUbergraph_GA_NPC_Parent_GrabPickup_Active) == 0x000004, "Wrong size on GA_NPC_Parent_GrabPickup_Active_C_ExecuteUbergraph_GA_NPC_Parent_GrabPickup_Active");
static_assert(offsetof(GA_NPC_Parent_GrabPickup_Active_C_ExecuteUbergraph_GA_NPC_Parent_GrabPickup_Active, EntryPoint) == 0x000000, "Member 'GA_NPC_Parent_GrabPickup_Active_C_ExecuteUbergraph_GA_NPC_Parent_GrabPickup_Active::EntryPoint' has a wrong offset!");

}

