#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_NPC_Parent_Spawn

#include "Basic.hpp"

#include "GA_NPC_Parent_classes.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_NPC_Parent_Spawn.GA_NPC_Parent_Spawn_C
// 0x0018 (0x0DC8 - 0x0DB0)
class UGA_NPC_Parent_Spawn_C : public UGA_NPC_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_NPC_Parent_Spawn_C;              // 0x0DB0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<struct FGameplayTag>                   WeakPointsToActivateDuringAbility;                 // 0x0DB8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_GA_NPC_Parent_Spawn(int32 EntryPoint);
	void SpawnAbilityTrigger(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void NPC_SpawnMontageCompletedOrCancelled();
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();
	void Triggered_8477F6014312EEDD75DB15AE82DA4B6A(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void Cancelled_8477F6014312EEDD75DB15AE82DA4B6A(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void Completed_8477F6014312EEDD75DB15AE82DA4B6A(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void SetWeakpointsActive(bool SetActive);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_NPC_Parent_Spawn_C">();
	}
	static class UGA_NPC_Parent_Spawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_NPC_Parent_Spawn_C>();
	}
};
static_assert(alignof(UGA_NPC_Parent_Spawn_C) == 0x000008, "Wrong alignment on UGA_NPC_Parent_Spawn_C");
static_assert(sizeof(UGA_NPC_Parent_Spawn_C) == 0x000DC8, "Wrong size on UGA_NPC_Parent_Spawn_C");
static_assert(offsetof(UGA_NPC_Parent_Spawn_C, UberGraphFrame_GA_NPC_Parent_Spawn_C) == 0x000DB0, "Member 'UGA_NPC_Parent_Spawn_C::UberGraphFrame_GA_NPC_Parent_Spawn_C' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_Spawn_C, WeakPointsToActivateDuringAbility) == 0x000DB8, "Member 'UGA_NPC_Parent_Spawn_C::WeakPointsToActivateDuringAbility' has a wrong offset!");

}

