#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_NPC_Irwin_Prey_Nug_TurnTransition

#include "Basic.hpp"

#include "GA_NPC_Parent_TurnTransition_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_NPC_Irwin_Prey_Nug_TurnTransition.GA_NPC_Irwin_Prey_Nug_TurnTransition_C
// 0x0000 (0x0AD8 - 0x0AD8)
class UGA_NPC_Irwin_Prey_Nug_TurnTransition_C final : public UGA_NPC_Parent_TurnTransition_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_NPC_Irwin_Prey_Nug_TurnTransition_C">();
	}
	static class UGA_NPC_Irwin_Prey_Nug_TurnTransition_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_NPC_Irwin_Prey_Nug_TurnTransition_C>();
	}
};
static_assert(alignof(UGA_NPC_Irwin_Prey_Nug_TurnTransition_C) == 0x000008, "Wrong alignment on UGA_NPC_Irwin_Prey_Nug_TurnTransition_C");
static_assert(sizeof(UGA_NPC_Irwin_Prey_Nug_TurnTransition_C) == 0x000AD8, "Wrong size on UGA_NPC_Irwin_Prey_Nug_TurnTransition_C");

}

