#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_NPC_Parent_GrabPickup

#include "Basic.hpp"

#include "GA_NPC_Parent_classes.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "AIModule_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_NPC_Parent_GrabPickup.GA_NPC_Parent_GrabPickup_C
// 0x0090 (0x0E40 - 0x0DB0)
class UGA_NPC_Parent_GrabPickup_C : public UGA_NPC_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_NPC_Parent_GrabPickup_C;         // 0x0DB0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AFortAIController*                      ActivatingAIController;                            // 0x0DB8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 GoalActor;                                         // 0x0DC0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          GrabPickupMontageActive;                           // 0x0DC8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          RootPushActive;                                    // 0x0DC9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          MoveToPickupFailed;                                // 0x0DCA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_DCB[0x5];                                      // 0x0DCB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityTask_ApplyRootMotionConstantForce* RootPushMoveTask;                                  // 0x0DD0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAbilityTask_MoveAI*                GrabPickupMoveTask;                                // 0x0DD8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AttachPickupInsteadOfGrabbing;                     // 0x0DE0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          DestroyPickupInsteadOfGrabbing;                    // 0x0DE1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_DE2[0x6];                                      // 0x0DE2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 GrabPickupMoveNavFilterClass;                      // 0x0DE8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         AdditionalMoveAcceptanceRadius;                    // 0x0DF0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RootPushDuration;                                  // 0x0DF4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PickupFlyTimeOverride;                             // 0x0DF8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DFC[0x4];                                      // 0x0DFC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UClass*>                         AdditionalPickupClassesWeHopeToGrabAlongWithOurGoalActor; // 0x0E00(0x0010)(Edit, BlueprintVisible)
	class UBoxComponent*                          GrabPickupOverlapBox;                              // 0x0E10(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AFortPickup*>                    FortPickupsWeAreGrabbing;                          // 0x0E18(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	struct FGameplayTag                           DestroyedPickupGC;                                 // 0x0E28(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)
	bool                                          UseSkeletalMeshIndexOnDestroyedPickupGC;           // 0x0E30(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E31[0x3];                                      // 0x0E31(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           FortPickupGrabForbiddenTags;                       // 0x0E34(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_NPC_Parent_GrabPickup(int32 EntryPoint);
	void UnbindPickupGrabbed(const TArray<class AActor*>& Pickups);
	void BindPickupGrabbed(const TArray<class AActor*>& Pickups);
	void PickupGrabbed(class AActor* Actor, EEndPlayReason EndPlayReason);
	void RootPushFinished();
	void GrabPickupMontageCancelled();
	void GrabPickupMontageCompleted();
	void GrabPickupMontageTriggered();
	void RunGrabPickupLogic(class UObject* OptionalObject);
	void StartMoveToPickup();
	void PlayGrabPickupMontage();
	void TryRootPushMovement();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnFinish_98FB6E3B40DA4F7A069C67BDE7146F67();
	void Triggered_DD39747D49B500836AC22C91D1178B8E(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void Cancelled_DD39747D49B500836AC22C91D1178B8E(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void Completed_DD39747D49B500836AC22C91D1178B8E(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void OnComplete_15DA46604030A25221952D98CB2C98B6();
	void OnInterrupted_15DA46604030A25221952D98CB2C98B6();
	void OnCancelled_15DA46604030A25221952D98CB2C98B6();
	void OnRequestFailed_15DA46604030A25221952D98CB2C98B6();
	void OnMoveFinished_15DA46604030A25221952D98CB2C98B6(EPathFollowingResult Result, class AAIController* AIController);
	void NPC_TryToEndGrabPickupAbility(const class FString& Reason);
	void NPC_SetupAbility();
	void NPC__GrabPickup(class AActor* ActorToGrab);
	void NPC_TryToGrabNonPickup(class AActor* ActorToTryToGrab);
	void NPC_SetGrabPickupOverlapBox();
	void NPC_OpenBuildingContainer(class ABuildingContainer* BuildingContainer, bool* Success);
	void NPC_PlayGCOnActorWhenDestroyingPickup();
	bool IsPickupGrabbedForbidden(class AFortPickup* FortPickup);

	void GetMoveAcceptableRadius(float* Radius) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_NPC_Parent_GrabPickup_C">();
	}
	static class UGA_NPC_Parent_GrabPickup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_NPC_Parent_GrabPickup_C>();
	}
};
static_assert(alignof(UGA_NPC_Parent_GrabPickup_C) == 0x000008, "Wrong alignment on UGA_NPC_Parent_GrabPickup_C");
static_assert(sizeof(UGA_NPC_Parent_GrabPickup_C) == 0x000E40, "Wrong size on UGA_NPC_Parent_GrabPickup_C");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, UberGraphFrame_GA_NPC_Parent_GrabPickup_C) == 0x000DB0, "Member 'UGA_NPC_Parent_GrabPickup_C::UberGraphFrame_GA_NPC_Parent_GrabPickup_C' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, ActivatingAIController) == 0x000DB8, "Member 'UGA_NPC_Parent_GrabPickup_C::ActivatingAIController' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, GoalActor) == 0x000DC0, "Member 'UGA_NPC_Parent_GrabPickup_C::GoalActor' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, GrabPickupMontageActive) == 0x000DC8, "Member 'UGA_NPC_Parent_GrabPickup_C::GrabPickupMontageActive' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, RootPushActive) == 0x000DC9, "Member 'UGA_NPC_Parent_GrabPickup_C::RootPushActive' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, MoveToPickupFailed) == 0x000DCA, "Member 'UGA_NPC_Parent_GrabPickup_C::MoveToPickupFailed' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, RootPushMoveTask) == 0x000DD0, "Member 'UGA_NPC_Parent_GrabPickup_C::RootPushMoveTask' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, GrabPickupMoveTask) == 0x000DD8, "Member 'UGA_NPC_Parent_GrabPickup_C::GrabPickupMoveTask' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, AttachPickupInsteadOfGrabbing) == 0x000DE0, "Member 'UGA_NPC_Parent_GrabPickup_C::AttachPickupInsteadOfGrabbing' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, DestroyPickupInsteadOfGrabbing) == 0x000DE1, "Member 'UGA_NPC_Parent_GrabPickup_C::DestroyPickupInsteadOfGrabbing' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, GrabPickupMoveNavFilterClass) == 0x000DE8, "Member 'UGA_NPC_Parent_GrabPickup_C::GrabPickupMoveNavFilterClass' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, AdditionalMoveAcceptanceRadius) == 0x000DF0, "Member 'UGA_NPC_Parent_GrabPickup_C::AdditionalMoveAcceptanceRadius' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, RootPushDuration) == 0x000DF4, "Member 'UGA_NPC_Parent_GrabPickup_C::RootPushDuration' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, PickupFlyTimeOverride) == 0x000DF8, "Member 'UGA_NPC_Parent_GrabPickup_C::PickupFlyTimeOverride' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, AdditionalPickupClassesWeHopeToGrabAlongWithOurGoalActor) == 0x000E00, "Member 'UGA_NPC_Parent_GrabPickup_C::AdditionalPickupClassesWeHopeToGrabAlongWithOurGoalActor' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, GrabPickupOverlapBox) == 0x000E10, "Member 'UGA_NPC_Parent_GrabPickup_C::GrabPickupOverlapBox' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, FortPickupsWeAreGrabbing) == 0x000E18, "Member 'UGA_NPC_Parent_GrabPickup_C::FortPickupsWeAreGrabbing' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, DestroyedPickupGC) == 0x000E28, "Member 'UGA_NPC_Parent_GrabPickup_C::DestroyedPickupGC' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, UseSkeletalMeshIndexOnDestroyedPickupGC) == 0x000E30, "Member 'UGA_NPC_Parent_GrabPickup_C::UseSkeletalMeshIndexOnDestroyedPickupGC' has a wrong offset!");
static_assert(offsetof(UGA_NPC_Parent_GrabPickup_C, FortPickupGrabForbiddenTags) == 0x000E34, "Member 'UGA_NPC_Parent_GrabPickup_C::FortPickupGrabForbiddenTags' has a wrong offset!");

}

