#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_TowerRun_Shake_Yogurt

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCNL_TowerRun_Shake_Yogurt.GCNL_TowerRun_Shake_Yogurt_C
// 0x0000 (0x07D0 - 0x07D0)
class AGCNL_TowerRun_Shake_Yogurt_C final : public AFortGameplayCueNotify_Loop
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCNL_TowerRun_Shake_Yogurt_C">();
	}
	static class AGCNL_TowerRun_Shake_Yogurt_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_TowerRun_Shake_Yogurt_C>();
	}
};
static_assert(alignof(AGCNL_TowerRun_Shake_Yogurt_C) == 0x000008, "Wrong alignment on AGCNL_TowerRun_Shake_Yogurt_C");
static_assert(sizeof(AGCNL_TowerRun_Shake_Yogurt_C) == 0x0007D0, "Wrong size on AGCNL_TowerRun_Shake_Yogurt_C");

}

