#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Bow_Bone_Damage_Athena

#include "Basic.hpp"

#include "GE_Athena_CustomDamage_Bow_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Bow_Bone_Damage_Athena.GE_Bow_Bone_Damage_Athena_C
// 0x0000 (0x0800 - 0x0800)
class UGE_Bow_Bone_Damage_Athena_C final : public UGE_Athena_CustomDamage_Bow_Generic_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Bow_Bone_Damage_Athena_C">();
	}
	static class UGE_Bow_Bone_Damage_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Bow_Bone_Damage_Athena_C>();
	}
};
static_assert(alignof(UGE_Bow_Bone_Damage_Athena_C) == 0x000008, "Wrong alignment on UGE_Bow_Bone_Damage_Athena_C");
static_assert(sizeof(UGE_Bow_Bone_Damage_Athena_C) == 0x000800, "Wrong size on UGE_Bow_Bone_Damage_Athena_C");

}

