#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HeldObjectLayerAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass HeldObjectLayerAnimBP.HeldObjectLayerAnimBP_C
// 0x25A0 (0x2920 - 0x0380)
class UHeldObjectLayerAnimBP_C final : public UFortItemLayerAnimInstance
{
public:
	uint8                                         Pad_378[0x8];                                      // 0x0378(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_34;                             // 0x0388(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_18;                  // 0x03B8(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_33;                             // 0x04D0(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_17;                  // 0x0500(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_32;                             // 0x0618(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_16;                  // 0x0648(0x0118)()
	struct FAnimNode_RotationOffsetBlendSpace     AnimGraphNode_RotationOffsetBlendSpace;            // 0x0760(0x0190)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_15;                  // 0x08F0(0x0118)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x0A08(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x0B60(0x0028)()
	struct FAnimNode_Root                         AnimGraphNode_Root_31;                             // 0x0B88(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_14;                  // 0x0BB8(0x0118)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x0CD0(0x0080)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x0D50(0x00A0)()
	struct FAnimNode_Root                         AnimGraphNode_Root_30;                             // 0x0DF0(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_13;                  // 0x0E20(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_29;                             // 0x0F38(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_12;                  // 0x0F68(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_28;                             // 0x1080(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_27;                             // 0x10B0(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_26;                             // 0x10E0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x1110(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_25;                             // 0x1190(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x11C0(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_24;                             // 0x1240(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x1270(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_23;                             // 0x12F0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x1320(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_22;                             // 0x13A0(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x13D0(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_21;                             // 0x1450(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x1480(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_20;                             // 0x1500(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x1530(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_19;                             // 0x15B0(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_18;                             // 0x15E0(0x0030)()
	struct FAnimNode_Root                         AnimGraphNode_Root_17;                             // 0x1610(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_11;                  // 0x1640(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_16;                             // 0x1758(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_10;                  // 0x1788(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_15;                             // 0x18A0(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_9;                   // 0x18D0(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_14;                             // 0x19E8(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_8;                   // 0x1A18(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_13;                             // 0x1B30(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_7;                   // 0x1B60(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_12;                             // 0x1C78(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_6;                   // 0x1CA8(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_11;                             // 0x1DC0(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_5;                   // 0x1DF0(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_10;                             // 0x1F08(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_4;                   // 0x1F38(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_9;                              // 0x2050(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x2080(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_8;                              // 0x2198(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x21C8(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_7;                              // 0x22E0(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x2310(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root_6;                              // 0x2428(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x2458(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_5;                              // 0x24D8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x2508(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x2588(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x25B8(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x2638(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x2668(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x26E8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x2718(0x0080)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x2798(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x27C8(0x0118)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x28E0(0x0030)()
	float                                         Pitch;                                             // 0x2910(0x0004)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Yaw;                                               // 0x2914(0x0004)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         AimOffsetAlpha;                                    // 0x2918(0x0004)(BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsHeldObjectDropped;                               // 0x291C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_HeldObjectLayerAnimBP(int32 EntryPoint);
	void BlueprintInitializeAnimation();
	void AnimNotify_HeldObjectPickUp();
	void AnimNotify_HeldObjectPlace();
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void ItemSkeletalControl(const struct FPoseLink& InPose, struct FPoseLink* ItemSkeletalControl_0);
	void ItemSwimJumpSurfaceEnd(struct FPoseLink* ItemSwimJumpSurfaceEnd_0);
	void ItemSwimJumpSurfaceLoop(struct FPoseLink* ItemSwimJumpSurfaceLoop_0);
	void ItemSwimJumpFallLoop(struct FPoseLink* ItemSwimJumpFallLoop_0);
	void ItemSwimJumpStartLoop(struct FPoseLink* ItemSwimJumpStartLoop_0);
	void ItemSwimJumpStart(struct FPoseLink* ItemSwimJumpStart_0);
	void ItemRelaxedEntry(const struct FPoseLink& InPoseRelaxedEntry, struct FPoseLink* ItemRelaxedEntry_0);
	void ItemLowerBodyJogPostPivot(const struct FPoseLink& InPoseLowerBodyJogPostPivot, struct FPoseLink* ItemLowerBodyJogPostPivot_0);
	void ItemLowerBodyJogPrePivot(const struct FPoseLink& InPoseLowerBodyJogPrePivot, struct FPoseLink* ItemLowerBodyJogPrePivot_0);
	void ItemLowerBodyJogStop(const struct FPoseLink& InPoseLowerBodyJogStop, struct FPoseLink* ItemLowerBodyJogStop_0);
	void ItemLowerBodyJogStart(const struct FPoseLink& InPoseLowerBodyJogStart, struct FPoseLink* ItemLowerBodyJogStart_0);
	void ItemLowerBodyLeanAdditive(const struct FPoseLink& InPoseLowerBodyLeanAdditive, struct FPoseLink* ItemLowerBodyLeanAdditive_0);
	void ItemLowerBodyMovement(const struct FPoseLink& InPoseLowerBodyMovement, struct FPoseLink* ItemLowerBodyMovement_0);
	void ItemJogPostPivotAdditive(const struct FPoseLink& InPosePostPivotAdditive, struct FPoseLink* ItemJogPostPivotAdditive_0);
	void ItemJogPrePivotAdditive(const struct FPoseLink& InPosePrePivotAdditive, struct FPoseLink* ItemJogPrePivotAdditive_0);
	void ItemJogStopAdditive(const struct FPoseLink& InPoseJogStopAdditive, struct FPoseLink* ItemJogStopAdditive_0);
	void ItemJogStartAdditive(const struct FPoseLink& InPoseJogStartAdditive, struct FPoseLink* ItemJogStartAdditive_0);
	void ItemFlyModeLoopAdditive(struct FPoseLink* ItemFlyModeLoopAdditive_0);
	void ItemFlyModeStartAdditive(struct FPoseLink* ItemFlyModeStartAdditive_0);
	void ItemZipLineStartAdditive(struct FPoseLink* ItemZipLineStartAdditive_0);
	void ItemJetPackJumpAdditive(struct FPoseLink* ItemJetPackJumpAdditive_0);
	void ItemJetPackStartAdditive(struct FPoseLink* ItemJetPackStartAdditive_0);
	void ItemFallLandAdditive(struct FPoseLink* ItemFallLandAdditive_0);
	void ItemFallAdditive(struct FPoseLink* ItemFallAdditive_0);
	void ItemJumpLoopAdditive(struct FPoseLink* ItemJumpLoopAdditive_0);
	void ItemJumpUpAdditive(struct FPoseLink* ItemJumpUpAdditive_0);
	void ItemSlopeSliding(struct FPoseLink* ItemSlopeSliding_0);
	void ItemCrouchTurningAdditive(struct FPoseLink* ItemCrouchTurningAdditive_0);
	void ItemIdleAdditive(const struct FPoseLink& InPoseIdleAdditive, struct FPoseLink* ItemIdleAdditive_0);
	void ItemFullBodySprint(const struct FPoseLink& InPoseSprint, struct FPoseLink* ItemFullBodySprint_0);
	void ItemUpperBody(const struct FPoseLink& InPoseUpperBody, const struct FFortAnimInput_AdjustedAim& InputParam, struct FPoseLink* ItemUpperBody_0);
	void ItemAimOffset(const struct FPoseLink& InPose_AimOffset, float AimOffsetAlpha_0, float Yaw_0, float Pitch_0, const struct FPoseLink& InPose_UpperLowerPreMeleeAO, struct FPoseLink* ItemAimOffset_0);
	void ItemFullBodyOverride(const struct FPoseLink& InPoseFullBody, struct FPoseLink* ItemFullBodyOverride_0);
	void ItemPreIK(const struct FPoseLink& InPose_PreIK, struct FPoseLink* ItemPreIK_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HeldObjectLayerAnimBP_C">();
	}
	static class UHeldObjectLayerAnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHeldObjectLayerAnimBP_C>();
	}
};
static_assert(alignof(UHeldObjectLayerAnimBP_C) == 0x000010, "Wrong alignment on UHeldObjectLayerAnimBP_C");
static_assert(sizeof(UHeldObjectLayerAnimBP_C) == 0x002920, "Wrong size on UHeldObjectLayerAnimBP_C");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, UberGraphFrame) == 0x000380, "Member 'UHeldObjectLayerAnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_34) == 0x000388, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_34' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_18) == 0x0003B8, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_18' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_33) == 0x0004D0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_33' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_17) == 0x000500, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_17' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_32) == 0x000618, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_32' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_16) == 0x000648, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_16' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_RotationOffsetBlendSpace) == 0x000760, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_RotationOffsetBlendSpace' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_15) == 0x0008F0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_15' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SaveCachedPose) == 0x000A08, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_UseCachedPose) == 0x000B60, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_31) == 0x000B88, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_31' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_14) == 0x000BB8, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_14' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_12) == 0x000CD0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_12' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_BlendListByBool) == 0x000D50, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_30) == 0x000DF0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_30' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_13) == 0x000E20, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_13' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_29) == 0x000F38, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_29' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_12) == 0x000F68, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_12' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_28) == 0x001080, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_28' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_27) == 0x0010B0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_27' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_26) == 0x0010E0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_26' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_11) == 0x001110, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_11' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_25) == 0x001190, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_25' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_10) == 0x0011C0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_10' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_24) == 0x001240, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_24' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_9) == 0x001270, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_9' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_23) == 0x0012F0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_23' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_8) == 0x001320, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_8' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_22) == 0x0013A0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_22' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_7) == 0x0013D0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_7' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_21) == 0x001450, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_21' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_6) == 0x001480, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_6' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_20) == 0x001500, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_20' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_5) == 0x001530, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_5' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_19) == 0x0015B0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_19' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_18) == 0x0015E0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_18' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_17) == 0x001610, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_17' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_11) == 0x001640, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_11' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_16) == 0x001758, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_16' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_10) == 0x001788, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_10' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_15) == 0x0018A0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_15' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_9) == 0x0018D0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_9' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_14) == 0x0019E8, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_14' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_8) == 0x001A18, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_8' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_13) == 0x001B30, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_13' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_7) == 0x001B60, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_7' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_12) == 0x001C78, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_12' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_6) == 0x001CA8, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_6' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_11) == 0x001DC0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_11' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_5) == 0x001DF0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_5' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_10) == 0x001F08, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_10' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_4) == 0x001F38, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_4' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_9) == 0x002050, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_9' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_3) == 0x002080, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_3' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_8) == 0x002198, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_8' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_2) == 0x0021C8, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_2' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_7) == 0x0022E0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_7' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose_1) == 0x002310, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose_1' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_6) == 0x002428, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_6' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_4) == 0x002458, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_4' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_5) == 0x0024D8, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_5' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_3) == 0x002508, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_3' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_4) == 0x002588, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_4' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_2) == 0x0025B8, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_2' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_3) == 0x002638, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_3' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer_1) == 0x002668, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer_1' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_2) == 0x0026E8, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_2' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_SequencePlayer) == 0x002718, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root_1) == 0x002798, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root_1' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_LinkedInputPose) == 0x0027C8, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AnimGraphNode_Root) == 0x0028E0, "Member 'UHeldObjectLayerAnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, Pitch) == 0x002910, "Member 'UHeldObjectLayerAnimBP_C::Pitch' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, Yaw) == 0x002914, "Member 'UHeldObjectLayerAnimBP_C::Yaw' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, AimOffsetAlpha) == 0x002918, "Member 'UHeldObjectLayerAnimBP_C::AimOffsetAlpha' has a wrong offset!");
static_assert(offsetof(UHeldObjectLayerAnimBP_C, IsHeldObjectDropped) == 0x00291C, "Member 'UHeldObjectLayerAnimBP_C::IsHeldObjectDropped' has a wrong offset!");

}

