#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Pawn_Irwin_Prey_Nug

#include "Basic.hpp"

#include "NPC_Pawn_Irwin_Prey_Nug_classes.hpp"
#include "NPC_Pawn_Irwin_Prey_Nug_parameters.hpp"


namespace SDK
{

// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.ExecuteUbergraph_NPC_Pawn_Irwin_Prey_Nug
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::ExecuteUbergraph_NPC_Pawn_Irwin_Prey_Nug(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "ExecuteUbergraph_NPC_Pawn_Irwin_Prey_Nug");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_ExecuteUbergraph_NPC_Pawn_Irwin_Prey_Nug Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_5_OnHeldObjectGuideProjectileStopped__DelegateSignature
// (BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_5_OnHeldObjectGuideProjectileStopped__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_5_OnHeldObjectGuideProjectileStopped__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_4_OnHeldObjectGuideProjectileStarted__DelegateSignature
// (BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_4_OnHeldObjectGuideProjectileStarted__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_4_OnHeldObjectGuideProjectileStarted__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.PlayPickUpAudio
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::PlayPickUpAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "PlayPickUpAudio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.PlayThrowAudio
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::PlayThrowAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "PlayThrowAudio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.OnHomingPassedTarget
// (Event, Public, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::OnHomingPassedTarget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "OnHomingPassedTarget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.OnReachedLockTargetDistanceThreshold
// (Event, Public, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::OnReachedLockTargetDistanceThreshold()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "OnReachedLockTargetDistanceThreshold");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.NPCNugUpdateStormHandling
// (BlueprintCallable, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::NPCNugUpdateStormHandling()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "NPCNugUpdateStormHandling");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetAccelerationMagnitude
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InAccelerationMagnitude                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetAccelerationMagnitude(class AActor* SelfActor, const float InAccelerationMagnitude)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetAccelerationMagnitude");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetAccelerationMagnitude Parms{};

	Parms.SelfActor = SelfActor;
	Parms.InAccelerationMagnitude = InAccelerationMagnitude;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.EventPickUpAudio
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     Event_Name                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::EventPickUpAudio(const struct FGameplayTag& Event_Name)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "EventPickUpAudio");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_EventPickUpAudio Parms{};

	Parms.Event_Name = std::move(Event_Name);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.EventThrowAudio
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     Event_Name                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::EventThrowAudio(const struct FGameplayTag& Event_Name)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "EventThrowAudio");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_EventThrowAudio Parms{};

	Parms.Event_Name = std::move(Event_Name);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetDesiredDirection
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Direction                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetDesiredDirection(class AActor* SelfActor, const struct FVector& Direction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetDesiredDirection");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetDesiredDirection Parms{};

	Parms.SelfActor = SelfActor;
	Parms.Direction = std::move(Direction);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetHomingData
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FProjectileHomingData            NewHomingData                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetHomingData(class AActor* SelfActor, const struct FProjectileHomingData& NewHomingData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetHomingData");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetHomingData Parms{};

	Parms.SelfActor = SelfActor;
	Parms.NewHomingData = std::move(NewHomingData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetHomingLaserTargetDistance
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewDistance                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetHomingLaserTargetDistance(class AActor* SelfActor, float NewDistance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetHomingLaserTargetDistance");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetHomingLaserTargetDistance Parms{};

	Parms.SelfActor = SelfActor;
	Parms.NewDistance = NewDistance;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.ResetChickenVars
// (BlueprintCallable, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::ResetChickenVars()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "ResetChickenVars");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.EnablePickUp
// (BlueprintCallable, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::EnablePickUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "EnablePickUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetHomingLockTargetDistanceThreshold
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewDistanceThreshold                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetHomingLockTargetDistanceThreshold(class AActor* SelfActor, float NewDistanceThreshold)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetHomingLockTargetDistanceThreshold");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetHomingLockTargetDistanceThreshold Parms{};

	Parms.SelfActor = SelfActor;
	Parms.NewDistanceThreshold = NewDistanceThreshold;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.On NPC PawnInteractedWith
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           AIPawn                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AFortPlayerPawn*                  InteractingPlayerPawn                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::On_NPC_PawnInteractedWith(class AActor* AIPawn, class AFortPlayerPawn* InteractingPlayerPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "On NPC PawnInteractedWith");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_On_NPC_PawnInteractedWith Parms{};

	Parms.AIPawn = AIPawn;
	Parms.InteractingPlayerPawn = InteractingPlayerPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetHomingTurnSpeedMin
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewTurnSpeedMin                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetHomingTurnSpeedMin(class AActor* SelfActor, float NewTurnSpeedMin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetHomingTurnSpeedMin");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetHomingTurnSpeedMin Parms{};

	Parms.SelfActor = SelfActor;
	Parms.NewTurnSpeedMin = NewTurnSpeedMin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetHomingTurnSpeedMax
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewTurnSpeedMin                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetHomingTurnSpeedMax(class AActor* SelfActor, float NewTurnSpeedMin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetHomingTurnSpeedMax");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetHomingTurnSpeedMax Parms{};

	Parms.SelfActor = SelfActor;
	Parms.NewTurnSpeedMin = NewTurnSpeedMin;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetHomingTimeUntilMaxTurnSpeed
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewTimeUntilMax                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetHomingTimeUntilMaxTurnSpeed(class AActor* SelfActor, float NewTimeUntilMax)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetHomingTimeUntilMaxTurnSpeed");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetHomingTimeUntilMaxTurnSpeed Parms{};

	Parms.SelfActor = SelfActor;
	Parms.NewTimeUntilMax = NewTimeUntilMax;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetHomingTargetPosition
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          HomingTargetPosition                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetHomingTargetPosition(class AActor* SelfActor, const struct FVector& HomingTargetPosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetHomingTargetPosition");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetHomingTargetPosition Parms{};

	Parms.SelfActor = SelfActor;
	Parms.HomingTargetPosition = std::move(HomingTargetPosition);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetHomingTargetOffset
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          NewHomingOffset                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetHomingTargetOffset(class AActor* SelfActor, const struct FVector& NewHomingOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetHomingTargetOffset");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetHomingTargetOffset Parms{};

	Parms.SelfActor = SelfActor;
	Parms.NewHomingOffset = std::move(NewHomingOffset);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetHomingTarget
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           HomingTarget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetHomingTarget(class AActor* SelfActor, class AActor* HomingTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetHomingTarget");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetHomingTarget Parms{};

	Parms.SelfActor = SelfActor;
	Parms.HomingTarget = HomingTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetHomingStyle
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           SelfActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortHomingStyle                        NewHomingStyle                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ResetHomingTurnSpeedTimer                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetHomingStyle(class AActor* SelfActor, EFortHomingStyle NewHomingStyle, bool ResetHomingTurnSpeedTimer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetHomingStyle");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetHomingStyle Parms{};

	Parms.SelfActor = SelfActor;
	Parms.NewHomingStyle = NewHomingStyle;
	Parms.ResetHomingTurnSpeedTimer = ResetHomingTurnSpeedTimer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.OnRep_bPawnPickedUp
// (BlueprintCallable, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::OnRep_bPawnPickedUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "OnRep_bPawnPickedUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.OnRep_bPawnThrown
// (BlueprintCallable, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::OnRep_bPawnThrown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "OnRep_bPawnThrown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.BindPlayerControllerOnUnpossess
// (Public, BlueprintCallable, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::BindPlayerControllerOnUnpossess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "BindPlayerControllerOnUnpossess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.Server Only Handle Player Controller OnUnPossess
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            PlayerPawn                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::Server_Only_Handle_Player_Controller_OnUnPossess(class APawn* PlayerPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "Server Only Handle Player Controller OnUnPossess");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_Server_Only_Handle_Player_Controller_OnUnPossess Parms{};

	Parms.PlayerPawn = PlayerPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.PlaySoundAudioTag
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayTag                     Event_Name                                             (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void ANPC_Pawn_Irwin_Prey_Nug_C::PlaySoundAudioTag(const struct FGameplayTag& Event_Name)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "PlaySoundAudioTag");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_PlaySoundAudioTag Parms{};

	Parms.Event_Name = std::move(Event_Name);

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.SetPawnMovementEnabled
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bEnabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ANPC_Pawn_Irwin_Prey_Nug_C::SetPawnMovementEnabled(bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "SetPawnMovementEnabled");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_SetPawnMovementEnabled Parms{};

	Parms.bEnabled = bEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.UpdateCollision
// (Public, BlueprintCallable, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::UpdateCollision()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "UpdateCollision");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.UpdateMovementComponents
// (Public, BlueprintCallable, BlueprintEvent)

void ANPC_Pawn_Irwin_Prey_Nug_C::UpdateMovementComponents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "UpdateMovementComponents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.BlueprintCanInteract
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class AFortPawn*                        InteractingPawn                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInteractionBeingAttempted              InteractionBeingAttempted                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ANPC_Pawn_Irwin_Prey_Nug_C::BlueprintCanInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "BlueprintCanInteract");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_BlueprintCanInteract Parms{};

	Parms.InteractingPawn = InteractingPawn;
	Parms.InteractionBeingAttempted = InteractionBeingAttempted;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.IsProjectileBeingKilled
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ANPC_Pawn_Irwin_Prey_Nug_C::IsProjectileBeingKilled() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "IsProjectileBeingKilled");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_IsProjectileBeingKilled Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.GetInstigatorPlayerController
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class AFortPlayerController*            ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class AFortPlayerController* ANPC_Pawn_Irwin_Prey_Nug_C::GetInstigatorPlayerController() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "GetInstigatorPlayerController");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_GetInstigatorPlayerController Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.GetFortProjectileMovementComponent
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UFortProjectileMovementComponent* ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UFortProjectileMovementComponent* ANPC_Pawn_Irwin_Prey_Nug_C::GetFortProjectileMovementComponent() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "GetFortProjectileMovementComponent");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_GetFortProjectileMovementComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C.GetCurrentLocation
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FVector ANPC_Pawn_Irwin_Prey_Nug_C::GetCurrentLocation() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_Pawn_Irwin_Prey_Nug_C", "GetCurrentLocation");

	Params::NPC_Pawn_Irwin_Prey_Nug_C_GetCurrentLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

