#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_Pawn_Irwin_Prey_Nug

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "NPC_Pawn_Wildlife_Prey_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NPC_Pawn_Irwin_Prey_Nug.NPC_Pawn_Irwin_Prey_Nug_C
// 0x0060 (0x2FF0 - 0x2F90)
class ANPC_Pawn_Irwin_Prey_Nug_C final : public ANPC_Pawn_Wildlife_Prey_Parent_C
{
public:
	uint8                                         Pad_2F81[0x7];                                     // 0x2F81(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_NPC_Pawn_Irwin_Prey_Nug_C;          // 0x2F88(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFTP_NPC_Assignment_Loot_Herbivore_C*   FTP_NPC_Assignment_Loot_Herbivore;                 // 0x2F90(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UFortHeldObjectComponent*               FortHeldObject;                                    // 0x2F98(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          bPawnPickedUp;                                     // 0x2FA0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	bool                                          bPawnThrown;                                       // 0x2FA1(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_2FA2[0x2];                                     // 0x2FA2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle            H_GE_PickedUp;                                     // 0x2FA4(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2FAC[0x4];                                     // 0x2FAC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 GE_ApplyPickupAbility;                             // 0x2FB0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  TC_BlockPickup;                                    // 0x2FB8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bIsPickupEnabled;                                  // 0x2FD8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2FD9[0x3];                                     // 0x2FD9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         PickupEnableDelay;                                 // 0x2FDC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PostLandDelay;                                     // 0x2FE0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_NPC_Pawn_Irwin_Prey_Nug(int32 EntryPoint);
	void BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_5_OnHeldObjectGuideProjectileStopped__DelegateSignature();
	void BndEvt__FortHeldObject_K2Node_ComponentBoundEvent_4_OnHeldObjectGuideProjectileStarted__DelegateSignature();
	void PlayPickUpAudio();
	void PlayThrowAudio();
	void OnHomingPassedTarget();
	void ReceiveBeginPlay();
	void OnReachedLockTargetDistanceThreshold();
	void NPCNugUpdateStormHandling();
	void SetAccelerationMagnitude(class AActor* SelfActor, const float InAccelerationMagnitude);
	void EventPickUpAudio(const struct FGameplayTag& Event_Name);
	void EventThrowAudio(const struct FGameplayTag& Event_Name);
	void SetDesiredDirection(class AActor* SelfActor, const struct FVector& Direction);
	void SetHomingData(class AActor* SelfActor, const struct FProjectileHomingData& NewHomingData);
	void SetHomingLaserTargetDistance(class AActor* SelfActor, float NewDistance);
	void ResetChickenVars();
	void EnablePickUp();
	void SetHomingLockTargetDistanceThreshold(class AActor* SelfActor, float NewDistanceThreshold);
	void On_NPC_PawnInteractedWith(class AActor* AIPawn, class AFortPlayerPawn* InteractingPlayerPawn);
	void SetHomingTurnSpeedMin(class AActor* SelfActor, float NewTurnSpeedMin);
	void SetHomingTurnSpeedMax(class AActor* SelfActor, float NewTurnSpeedMin);
	void SetHomingTimeUntilMaxTurnSpeed(class AActor* SelfActor, float NewTimeUntilMax);
	void SetHomingTargetPosition(class AActor* SelfActor, const struct FVector& HomingTargetPosition);
	void SetHomingTargetOffset(class AActor* SelfActor, const struct FVector& NewHomingOffset);
	void SetHomingTarget(class AActor* SelfActor, class AActor* HomingTarget);
	void SetHomingStyle(class AActor* SelfActor, EFortHomingStyle NewHomingStyle, bool ResetHomingTurnSpeedTimer);
	void OnRep_bPawnPickedUp();
	void OnRep_bPawnThrown();
	void BindPlayerControllerOnUnpossess();
	void Server_Only_Handle_Player_Controller_OnUnPossess(class APawn* PlayerPawn);
	void PlaySoundAudioTag(const struct FGameplayTag& Event_Name);
	void SetPawnMovementEnabled(bool bEnabled);
	void UpdateCollision();
	void UpdateMovementComponents();

	bool BlueprintCanInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted) const;
	bool IsProjectileBeingKilled() const;
	class AFortPlayerController* GetInstigatorPlayerController() const;
	class UFortProjectileMovementComponent* GetFortProjectileMovementComponent() const;
	struct FVector GetCurrentLocation() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NPC_Pawn_Irwin_Prey_Nug_C">();
	}
	static class ANPC_Pawn_Irwin_Prey_Nug_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANPC_Pawn_Irwin_Prey_Nug_C>();
	}
};
static_assert(alignof(ANPC_Pawn_Irwin_Prey_Nug_C) == 0x000010, "Wrong alignment on ANPC_Pawn_Irwin_Prey_Nug_C");
static_assert(sizeof(ANPC_Pawn_Irwin_Prey_Nug_C) == 0x002FF0, "Wrong size on ANPC_Pawn_Irwin_Prey_Nug_C");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, UberGraphFrame_NPC_Pawn_Irwin_Prey_Nug_C) == 0x002F88, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::UberGraphFrame_NPC_Pawn_Irwin_Prey_Nug_C' has a wrong offset!");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, FTP_NPC_Assignment_Loot_Herbivore) == 0x002F90, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::FTP_NPC_Assignment_Loot_Herbivore' has a wrong offset!");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, FortHeldObject) == 0x002F98, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::FortHeldObject' has a wrong offset!");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, bPawnPickedUp) == 0x002FA0, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::bPawnPickedUp' has a wrong offset!");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, bPawnThrown) == 0x002FA1, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::bPawnThrown' has a wrong offset!");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, H_GE_PickedUp) == 0x002FA4, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::H_GE_PickedUp' has a wrong offset!");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, GE_ApplyPickupAbility) == 0x002FB0, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::GE_ApplyPickupAbility' has a wrong offset!");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, TC_BlockPickup) == 0x002FB8, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::TC_BlockPickup' has a wrong offset!");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, bIsPickupEnabled) == 0x002FD8, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::bIsPickupEnabled' has a wrong offset!");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, PickupEnableDelay) == 0x002FDC, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::PickupEnableDelay' has a wrong offset!");
static_assert(offsetof(ANPC_Pawn_Irwin_Prey_Nug_C, PostLandDelay) == 0x002FE0, "Member 'ANPC_Pawn_Irwin_Prey_Nug_C::PostLandDelay' has a wrong offset!");

}

