#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Scrap_Bow_AnimBlueprint

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Scrap_Bow_AnimBlueprint.Scrap_Bow_AnimBlueprint_C
// 0x09D0 (0x0C90 - 0x02C0)
class UScrap_Bow_AnimBlueprint_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02C8(0x0030)()
	uint8                                         Pad_2F8[0x8];                                      // 0x02F8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody;                           // 0x0300(0x0830)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0B30(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x0B50(0x0118)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0C68(0x0020)()

public:
	void ExecuteUbergraph_Scrap_Bow_AnimBlueprint(int32 EntryPoint);
	void AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Scrap_Bow_AnimBlueprint_C">();
	}
	static class UScrap_Bow_AnimBlueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScrap_Bow_AnimBlueprint_C>();
	}
};
static_assert(alignof(UScrap_Bow_AnimBlueprint_C) == 0x000010, "Wrong alignment on UScrap_Bow_AnimBlueprint_C");
static_assert(sizeof(UScrap_Bow_AnimBlueprint_C) == 0x000C90, "Wrong size on UScrap_Bow_AnimBlueprint_C");
static_assert(offsetof(UScrap_Bow_AnimBlueprint_C, UberGraphFrame) == 0x0002C0, "Member 'UScrap_Bow_AnimBlueprint_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UScrap_Bow_AnimBlueprint_C, AnimGraphNode_Root) == 0x0002C8, "Member 'UScrap_Bow_AnimBlueprint_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UScrap_Bow_AnimBlueprint_C, AnimGraphNode_RigidBody) == 0x000300, "Member 'UScrap_Bow_AnimBlueprint_C::AnimGraphNode_RigidBody' has a wrong offset!");
static_assert(offsetof(UScrap_Bow_AnimBlueprint_C, AnimGraphNode_ComponentToLocalSpace) == 0x000B30, "Member 'UScrap_Bow_AnimBlueprint_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UScrap_Bow_AnimBlueprint_C, AnimGraphNode_LinkedInputPose) == 0x000B50, "Member 'UScrap_Bow_AnimBlueprint_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UScrap_Bow_AnimBlueprint_C, AnimGraphNode_LocalToComponentSpace) == 0x000C68, "Member 'UScrap_Bow_AnimBlueprint_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");

}

