#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SoundLibrary

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// Enum SoundLibrary.ESoundLibraryNotifyTriggerType
// NumValues: 0x0004
enum class ESoundLibraryNotifyTriggerType : uint8
{
	Play                                     = 0,
	Stop                                     = 1,
	None                                     = 2,
	ESoundLibraryNotifyTriggerType_MAX       = 3,
};

// ScriptStruct SoundLibrary.SoundLibraryAnimContextSettings
// 0x001C (0x001C - 0x0000)
struct FSoundLibraryAnimContextSettings final
{
public:
	struct FFloatInterval                         AnimRateThreshold;                                 // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FGameplayTag                           EventName;                                         // 0x0008(0x0008)(Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAttachToActor;                                    // 0x0010(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFadeOutOnEnd;                                     // 0x0011(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_12[0x2];                                       // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         FadeTime;                                          // 0x0014(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NotifyTriggerChance;                               // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FSoundLibraryAnimContextSettings) == 0x000004, "Wrong alignment on FSoundLibraryAnimContextSettings");
static_assert(sizeof(FSoundLibraryAnimContextSettings) == 0x00001C, "Wrong size on FSoundLibraryAnimContextSettings");
static_assert(offsetof(FSoundLibraryAnimContextSettings, AnimRateThreshold) == 0x000000, "Member 'FSoundLibraryAnimContextSettings::AnimRateThreshold' has a wrong offset!");
static_assert(offsetof(FSoundLibraryAnimContextSettings, EventName) == 0x000008, "Member 'FSoundLibraryAnimContextSettings::EventName' has a wrong offset!");
static_assert(offsetof(FSoundLibraryAnimContextSettings, bAttachToActor) == 0x000010, "Member 'FSoundLibraryAnimContextSettings::bAttachToActor' has a wrong offset!");
static_assert(offsetof(FSoundLibraryAnimContextSettings, bFadeOutOnEnd) == 0x000011, "Member 'FSoundLibraryAnimContextSettings::bFadeOutOnEnd' has a wrong offset!");
static_assert(offsetof(FSoundLibraryAnimContextSettings, FadeTime) == 0x000014, "Member 'FSoundLibraryAnimContextSettings::FadeTime' has a wrong offset!");
static_assert(offsetof(FSoundLibraryAnimContextSettings, NotifyTriggerChance) == 0x000018, "Member 'FSoundLibraryAnimContextSettings::NotifyTriggerChance' has a wrong offset!");

// ScriptStruct SoundLibrary.SoundLibraryPlaySoundResult
// 0x0030 (0x0030 - 0x0000)
struct FSoundLibraryPlaySoundResult final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bWasBlocked;                                       // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSuccess;                                          // 0x0009(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x16];                                       // 0x000A(0x0016)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UAudioComponent*>                AudioComponents;                                   // 0x0020(0x0010)(BlueprintVisible, ExportObject, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
static_assert(alignof(FSoundLibraryPlaySoundResult) == 0x000008, "Wrong alignment on FSoundLibraryPlaySoundResult");
static_assert(sizeof(FSoundLibraryPlaySoundResult) == 0x000030, "Wrong size on FSoundLibraryPlaySoundResult");
static_assert(offsetof(FSoundLibraryPlaySoundResult, bWasBlocked) == 0x000008, "Member 'FSoundLibraryPlaySoundResult::bWasBlocked' has a wrong offset!");
static_assert(offsetof(FSoundLibraryPlaySoundResult, bSuccess) == 0x000009, "Member 'FSoundLibraryPlaySoundResult::bSuccess' has a wrong offset!");
static_assert(offsetof(FSoundLibraryPlaySoundResult, AudioComponents) == 0x000020, "Member 'FSoundLibraryPlaySoundResult::AudioComponents' has a wrong offset!");

// ScriptStruct SoundLibrary.SoundLibraryActorData
// 0x0038 (0x0038 - 0x0000)
struct alignas(0x08) FSoundLibraryActorData final
{
public:
	uint8                                         Pad_0[0x38];                                       // 0x0000(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FSoundLibraryActorData) == 0x000008, "Wrong alignment on FSoundLibraryActorData");
static_assert(sizeof(FSoundLibraryActorData) == 0x000038, "Wrong size on FSoundLibraryActorData");

// ScriptStruct SoundLibrary.SimpleSoundLibraryContextSettings
// 0x000C (0x000C - 0x0000)
struct FSimpleSoundLibraryContextSettings final
{
public:
	struct FGameplayTag                           EventName;                                         // 0x0000(0x0008)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIs1P;                                             // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceComponentCreation;                           // 0x0009(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FSimpleSoundLibraryContextSettings) == 0x000004, "Wrong alignment on FSimpleSoundLibraryContextSettings");
static_assert(sizeof(FSimpleSoundLibraryContextSettings) == 0x00000C, "Wrong size on FSimpleSoundLibraryContextSettings");
static_assert(offsetof(FSimpleSoundLibraryContextSettings, EventName) == 0x000000, "Member 'FSimpleSoundLibraryContextSettings::EventName' has a wrong offset!");
static_assert(offsetof(FSimpleSoundLibraryContextSettings, bIs1P) == 0x000008, "Member 'FSimpleSoundLibraryContextSettings::bIs1P' has a wrong offset!");
static_assert(offsetof(FSimpleSoundLibraryContextSettings, bForceComponentCreation) == 0x000009, "Member 'FSimpleSoundLibraryContextSettings::bForceComponentCreation' has a wrong offset!");

}

