#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VoiceChannelHeader

#include "Basic.hpp"

#include "VoiceChannelHeader_classes.hpp"
#include "VoiceChannelHeader_parameters.hpp"


namespace SDK
{

// Function VoiceChannelHeader.VoiceChannelHeader_C.ExecuteUbergraph_VoiceChannelHeader
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UVoiceChannelHeader_C::ExecuteUbergraph_VoiceChannelHeader(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VoiceChannelHeader_C", "ExecuteUbergraph_VoiceChannelHeader");

	Params::VoiceChannelHeader_C_ExecuteUbergraph_VoiceChannelHeader Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VoiceChannelHeader.VoiceChannelHeader_C.OnUpdateVisuals
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsActive                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bIsListening                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UVoiceChannelHeader_C::OnUpdateVisuals(bool bIsActive, bool bIsListening)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VoiceChannelHeader_C", "OnUpdateVisuals");

	Params::VoiceChannelHeader_C_OnUpdateVisuals Parms{};

	Parms.bIsActive = bIsActive;
	Parms.bIsListening = bIsListening;

	UObject::ProcessEvent(Func, &Parms);
}


// Function VoiceChannelHeader.VoiceChannelHeader_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UVoiceChannelHeader_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VoiceChannelHeader_C", "PreConstruct");

	Params::VoiceChannelHeader_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

