#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WrapBandages_Prop_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass WrapBandages_Prop_AnimBP.WrapBandages_Prop_AnimBP_C
// 0x03A0 (0x0700 - 0x0360)
class UWrapBandages_Prop_AnimBP_C final : public UFortItemAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0360(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0368(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0398(0x0080)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x0418(0x0048)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum;                     // 0x0460(0x00B0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x0510(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x0668(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x0690(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x06B8(0x0048)()

public:
	void ExecuteUbergraph_WrapBandages_Prop_AnimBP(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WrapBandages_Prop_AnimBP_C">();
	}
	static class UWrapBandages_Prop_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWrapBandages_Prop_AnimBP_C>();
	}
};
static_assert(alignof(UWrapBandages_Prop_AnimBP_C) == 0x000010, "Wrong alignment on UWrapBandages_Prop_AnimBP_C");
static_assert(sizeof(UWrapBandages_Prop_AnimBP_C) == 0x000700, "Wrong size on UWrapBandages_Prop_AnimBP_C");
static_assert(offsetof(UWrapBandages_Prop_AnimBP_C, UberGraphFrame) == 0x000360, "Member 'UWrapBandages_Prop_AnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWrapBandages_Prop_AnimBP_C, AnimGraphNode_Root) == 0x000368, "Member 'UWrapBandages_Prop_AnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UWrapBandages_Prop_AnimBP_C, AnimGraphNode_SequencePlayer) == 0x000398, "Member 'UWrapBandages_Prop_AnimBP_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(UWrapBandages_Prop_AnimBP_C, AnimGraphNode_Slot_1) == 0x000418, "Member 'UWrapBandages_Prop_AnimBP_C::AnimGraphNode_Slot_1' has a wrong offset!");
static_assert(offsetof(UWrapBandages_Prop_AnimBP_C, AnimGraphNode_BlendListByEnum) == 0x000460, "Member 'UWrapBandages_Prop_AnimBP_C::AnimGraphNode_BlendListByEnum' has a wrong offset!");
static_assert(offsetof(UWrapBandages_Prop_AnimBP_C, AnimGraphNode_SaveCachedPose) == 0x000510, "Member 'UWrapBandages_Prop_AnimBP_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UWrapBandages_Prop_AnimBP_C, AnimGraphNode_UseCachedPose_1) == 0x000668, "Member 'UWrapBandages_Prop_AnimBP_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(UWrapBandages_Prop_AnimBP_C, AnimGraphNode_UseCachedPose) == 0x000690, "Member 'UWrapBandages_Prop_AnimBP_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UWrapBandages_Prop_AnimBP_C, AnimGraphNode_Slot) == 0x0006B8, "Member 'UWrapBandages_Prop_AnimBP_C::AnimGraphNode_Slot' has a wrong offset!");

}

